// <auto-generated> by gen_abi.py; edit the generator, not this file. </auto-generated>
#nullable disable warnings
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;

namespace SharpFuzzHarness;

/// <summary>
/// The managed / unmanaged call boundary without any native library: unmanaged function pointers to
/// [UnmanagedCallersOnly] methods (managed-to-unmanaged call, unmanaged-to-managed entry) with structs
/// of every SysV classification passed and returned by value, scalar signatures that spill to the
/// stack, small integers (sign extension), Half / Int128 / decimal / Guid; delegates from function
/// pointers; and delegate thunks (Marshal.GetFunctionPointerForDelegate) whose reverse stubs marshal
/// strings, arrays (from guarded native memory), bools, chars, by-ref and non-blittable structs.
/// </summary>
/// <remarks>Input layout: byte 0 = case, rest = values (structs are filled from the raw bytes).</remarks>
public static unsafe partial class AbiTarget
{
    [StructLayout(LayoutKind.Sequential)] public struct S4 { public int A; }
    [StructLayout(LayoutKind.Sequential)] public struct S8 { public int A; public float B; }
    [StructLayout(LayoutKind.Sequential)] public struct S8D { public double D; }
    [StructLayout(LayoutKind.Sequential)] public struct S12 { public int A; public int B; public int C; }
    [StructLayout(LayoutKind.Sequential)] public struct S16 { public long A; public double B; }
    [StructLayout(LayoutKind.Sequential)] public struct S16D { public double A; public double B; }
    [StructLayout(LayoutKind.Sequential)] public struct S16F { public float A; public float B; public float C; public float D; }
    [StructLayout(LayoutKind.Sequential)] public struct S20 { public int A; public int B; public int C; public int D; public int E; }
    [StructLayout(LayoutKind.Sequential)] public struct S24 { public long A; public double B; public long C; }
    [StructLayout(LayoutKind.Sequential)] public struct S32 { public double A; public double B; public double C; public double D; }
    [StructLayout(LayoutKind.Sequential)] public struct S3 { public byte A; public byte B; public byte C; }
    [StructLayout(LayoutKind.Sequential)] public struct S6 { public short A; public short B; public short C; }
    [StructLayout(LayoutKind.Sequential)] public struct S7 { public byte A; public byte B; public byte C; public byte D; public byte E; public byte F; public byte G; }
    [StructLayout(LayoutKind.Sequential)] public struct S9 { public byte A; public long B; }
    [StructLayout(LayoutKind.Sequential)] public struct SFI { public float A; public int B; }
    [StructLayout(LayoutKind.Sequential)] public struct SDI { public double A; public int B; }
    [StructLayout(LayoutKind.Sequential)] public struct SNested { public S8 Inner; public long L; }
    [StructLayout(LayoutKind.Sequential)] public struct SHalf { public Half H; }
    [StructLayout(LayoutKind.Sequential)] public struct SGuid { public Guid G; }
    [StructLayout(LayoutKind.Sequential)] public struct SPtrB { public nint P; public byte B; }
    [StructLayout(LayoutKind.Sequential)] public struct SFloat3 { public float A; public float B; public float C; }
    [StructLayout(LayoutKind.Sequential)] public struct SDoubleFloat { public double A; public float B; }
    [StructLayout(LayoutKind.Sequential)] public struct SByteFloat { public byte A; public float B; }
    [StructLayout(LayoutKind.Sequential)] public struct SLongByte { public long A; public byte B; }
    [StructLayout(LayoutKind.Sequential)] public struct SFloatLong { public float A; public long B; }
    [StructLayout(LayoutKind.Sequential)] public struct SHalf3 { public Half A; public Half B; public Half C; }
    [StructLayout(LayoutKind.Sequential)] public struct S40 { public long A; public long B; public long C; public long D; public long E; }
    [StructLayout(LayoutKind.Sequential)] public struct SNested24 { public S12 X; public S12 Y; }

    public static long Fold(decimal d) { int[] b = decimal.GetBits(d); return b[0] + 3L * b[1] + 5L * b[2] + 7L * b[3]; }
    public static long Fold(Guid g) { Span<byte> b = stackalloc byte[16]; g.TryWriteBytes(b); return Fold(b); }
    public static long Fold(ReadOnlySpan<byte> b) { long h = 0; foreach (byte x in b) h = h * 31 + x; return h; }
    public static long Fold(S4 s) => unchecked(((long)s.A) * 3);
    public static long Fold(S8 s) => unchecked(((long)s.A) * 3 + (BitConverter.SingleToInt32Bits(s.B)) * 5);
    public static long Fold(S8D s) => unchecked((BitConverter.DoubleToInt64Bits(s.D)) * 3);
    public static long Fold(S12 s) => unchecked(((long)s.A) * 3 + ((long)s.B) * 5 + ((long)s.C) * 7);
    public static long Fold(S16 s) => unchecked((s.A) * 3 + (BitConverter.DoubleToInt64Bits(s.B)) * 5);
    public static long Fold(S16D s) => unchecked((BitConverter.DoubleToInt64Bits(s.A)) * 3 + (BitConverter.DoubleToInt64Bits(s.B)) * 5);
    public static long Fold(S16F s) => unchecked((BitConverter.SingleToInt32Bits(s.A)) * 3 + (BitConverter.SingleToInt32Bits(s.B)) * 5 + (BitConverter.SingleToInt32Bits(s.C)) * 7 + (BitConverter.SingleToInt32Bits(s.D)) * 9);
    public static long Fold(S20 s) => unchecked(((long)s.A) * 3 + ((long)s.B) * 5 + ((long)s.C) * 7 + ((long)s.D) * 9 + ((long)s.E) * 11);
    public static long Fold(S24 s) => unchecked((s.A) * 3 + (BitConverter.DoubleToInt64Bits(s.B)) * 5 + (s.C) * 7);
    public static long Fold(S32 s) => unchecked((BitConverter.DoubleToInt64Bits(s.A)) * 3 + (BitConverter.DoubleToInt64Bits(s.B)) * 5 + (BitConverter.DoubleToInt64Bits(s.C)) * 7 + (BitConverter.DoubleToInt64Bits(s.D)) * 9);
    public static long Fold(S3 s) => unchecked(((long)s.A) * 3 + ((long)s.B) * 5 + ((long)s.C) * 7);
    public static long Fold(S6 s) => unchecked(((long)s.A) * 3 + ((long)s.B) * 5 + ((long)s.C) * 7);
    public static long Fold(S7 s) => unchecked(((long)s.A) * 3 + ((long)s.B) * 5 + ((long)s.C) * 7 + ((long)s.D) * 9 + ((long)s.E) * 11 + ((long)s.F) * 13 + ((long)s.G) * 15);
    public static long Fold(S9 s) => unchecked(((long)s.A) * 3 + (s.B) * 5);
    public static long Fold(SFI s) => unchecked((BitConverter.SingleToInt32Bits(s.A)) * 3 + ((long)s.B) * 5);
    public static long Fold(SDI s) => unchecked((BitConverter.DoubleToInt64Bits(s.A)) * 3 + ((long)s.B) * 5);
    public static long Fold(SNested s) => unchecked((Fold(s.Inner)) * 3 + (s.L) * 5);
    public static long Fold(SHalf s) => unchecked((BitConverter.HalfToInt16Bits(s.H)) * 3);
    public static long Fold(SGuid s) => unchecked((Fold(s.G)) * 3);
    public static long Fold(SPtrB s) => unchecked(((long)s.P) * 3 + ((long)s.B) * 5);
    public static long Fold(SFloat3 s) => unchecked((BitConverter.SingleToInt32Bits(s.A)) * 3 + (BitConverter.SingleToInt32Bits(s.B)) * 5 + (BitConverter.SingleToInt32Bits(s.C)) * 7);
    public static long Fold(SDoubleFloat s) => unchecked((BitConverter.DoubleToInt64Bits(s.A)) * 3 + (BitConverter.SingleToInt32Bits(s.B)) * 5);
    public static long Fold(SByteFloat s) => unchecked(((long)s.A) * 3 + (BitConverter.SingleToInt32Bits(s.B)) * 5);
    public static long Fold(SLongByte s) => unchecked((s.A) * 3 + ((long)s.B) * 5);
    public static long Fold(SFloatLong s) => unchecked((BitConverter.SingleToInt32Bits(s.A)) * 3 + (s.B) * 5);
    public static long Fold(SHalf3 s) => unchecked((BitConverter.HalfToInt16Bits(s.A)) * 3 + (BitConverter.HalfToInt16Bits(s.B)) * 5 + (BitConverter.HalfToInt16Bits(s.C)) * 7);
    public static long Fold(S40 s) => unchecked((s.A) * 3 + (s.B) * 5 + (s.C) * 7 + (s.D) * 9 + (s.E) * 11);
    public static long Fold(SNested24 s) => unchecked((Fold(s.X)) * 3 + (Fold(s.Y)) * 5);

    private static T Read<T>(ref FuzzInput input) where T : unmanaged
    {
        T value = default;
        Span<byte> bytes = MemoryMarshal.AsBytes(new Span<T>(ref value));
        input.Bytes(bytes.Length).CopyTo(bytes);
        return value;
    }

    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S4 EchoS4(S4 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS4(int a, S4 s, double d, S4 t, long l, S4 u, float f, S4 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS4(S4 s0, S4 s1, S4 s2, S4 s3, S4 s4, S4 s5, S4 s6, S4 s7, S4 s8, S4 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S4 PickS4(long which, S4 a, S4 b, S4 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S8 EchoS8(S8 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS8(int a, S8 s, double d, S8 t, long l, S8 u, float f, S8 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS8(S8 s0, S8 s1, S8 s2, S8 s3, S8 s4, S8 s5, S8 s6, S8 s7, S8 s8, S8 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S8 PickS8(long which, S8 a, S8 b, S8 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S8D EchoS8D(S8D s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS8D(int a, S8D s, double d, S8D t, long l, S8D u, float f, S8D v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS8D(S8D s0, S8D s1, S8D s2, S8D s3, S8D s4, S8D s5, S8D s6, S8D s7, S8D s8, S8D s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S8D PickS8D(long which, S8D a, S8D b, S8D c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S12 EchoS12(S12 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS12(int a, S12 s, double d, S12 t, long l, S12 u, float f, S12 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS12(S12 s0, S12 s1, S12 s2, S12 s3, S12 s4, S12 s5, S12 s6, S12 s7, S12 s8, S12 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S12 PickS12(long which, S12 a, S12 b, S12 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S16 EchoS16(S16 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS16(int a, S16 s, double d, S16 t, long l, S16 u, float f, S16 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS16(S16 s0, S16 s1, S16 s2, S16 s3, S16 s4, S16 s5, S16 s6, S16 s7, S16 s8, S16 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S16 PickS16(long which, S16 a, S16 b, S16 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S16D EchoS16D(S16D s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS16D(int a, S16D s, double d, S16D t, long l, S16D u, float f, S16D v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS16D(S16D s0, S16D s1, S16D s2, S16D s3, S16D s4, S16D s5, S16D s6, S16D s7, S16D s8, S16D s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S16D PickS16D(long which, S16D a, S16D b, S16D c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S16F EchoS16F(S16F s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS16F(int a, S16F s, double d, S16F t, long l, S16F u, float f, S16F v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS16F(S16F s0, S16F s1, S16F s2, S16F s3, S16F s4, S16F s5, S16F s6, S16F s7, S16F s8, S16F s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S16F PickS16F(long which, S16F a, S16F b, S16F c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S20 EchoS20(S20 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS20(int a, S20 s, double d, S20 t, long l, S20 u, float f, S20 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS20(S20 s0, S20 s1, S20 s2, S20 s3, S20 s4, S20 s5, S20 s6, S20 s7, S20 s8, S20 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S20 PickS20(long which, S20 a, S20 b, S20 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S24 EchoS24(S24 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS24(int a, S24 s, double d, S24 t, long l, S24 u, float f, S24 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS24(S24 s0, S24 s1, S24 s2, S24 s3, S24 s4, S24 s5, S24 s6, S24 s7, S24 s8, S24 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S24 PickS24(long which, S24 a, S24 b, S24 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S32 EchoS32(S32 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS32(int a, S32 s, double d, S32 t, long l, S32 u, float f, S32 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS32(S32 s0, S32 s1, S32 s2, S32 s3, S32 s4, S32 s5, S32 s6, S32 s7, S32 s8, S32 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S32 PickS32(long which, S32 a, S32 b, S32 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S3 EchoS3(S3 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS3(int a, S3 s, double d, S3 t, long l, S3 u, float f, S3 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS3(S3 s0, S3 s1, S3 s2, S3 s3, S3 s4, S3 s5, S3 s6, S3 s7, S3 s8, S3 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S3 PickS3(long which, S3 a, S3 b, S3 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S6 EchoS6(S6 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS6(int a, S6 s, double d, S6 t, long l, S6 u, float f, S6 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS6(S6 s0, S6 s1, S6 s2, S6 s3, S6 s4, S6 s5, S6 s6, S6 s7, S6 s8, S6 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S6 PickS6(long which, S6 a, S6 b, S6 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S7 EchoS7(S7 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS7(int a, S7 s, double d, S7 t, long l, S7 u, float f, S7 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS7(S7 s0, S7 s1, S7 s2, S7 s3, S7 s4, S7 s5, S7 s6, S7 s7, S7 s8, S7 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S7 PickS7(long which, S7 a, S7 b, S7 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S9 EchoS9(S9 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS9(int a, S9 s, double d, S9 t, long l, S9 u, float f, S9 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS9(S9 s0, S9 s1, S9 s2, S9 s3, S9 s4, S9 s5, S9 s6, S9 s7, S9 s8, S9 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S9 PickS9(long which, S9 a, S9 b, S9 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SFI EchoSFI(SFI s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSFI(int a, SFI s, double d, SFI t, long l, SFI u, float f, SFI v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySFI(SFI s0, SFI s1, SFI s2, SFI s3, SFI s4, SFI s5, SFI s6, SFI s7, SFI s8, SFI s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SFI PickSFI(long which, SFI a, SFI b, SFI c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SDI EchoSDI(SDI s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSDI(int a, SDI s, double d, SDI t, long l, SDI u, float f, SDI v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySDI(SDI s0, SDI s1, SDI s2, SDI s3, SDI s4, SDI s5, SDI s6, SDI s7, SDI s8, SDI s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SDI PickSDI(long which, SDI a, SDI b, SDI c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SNested EchoSNested(SNested s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSNested(int a, SNested s, double d, SNested t, long l, SNested u, float f, SNested v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySNested(SNested s0, SNested s1, SNested s2, SNested s3, SNested s4, SNested s5, SNested s6, SNested s7, SNested s8, SNested s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SNested PickSNested(long which, SNested a, SNested b, SNested c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SHalf EchoSHalf(SHalf s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSHalf(int a, SHalf s, double d, SHalf t, long l, SHalf u, float f, SHalf v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySHalf(SHalf s0, SHalf s1, SHalf s2, SHalf s3, SHalf s4, SHalf s5, SHalf s6, SHalf s7, SHalf s8, SHalf s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SHalf PickSHalf(long which, SHalf a, SHalf b, SHalf c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SGuid EchoSGuid(SGuid s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSGuid(int a, SGuid s, double d, SGuid t, long l, SGuid u, float f, SGuid v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySGuid(SGuid s0, SGuid s1, SGuid s2, SGuid s3, SGuid s4, SGuid s5, SGuid s6, SGuid s7, SGuid s8, SGuid s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SGuid PickSGuid(long which, SGuid a, SGuid b, SGuid c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SPtrB EchoSPtrB(SPtrB s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSPtrB(int a, SPtrB s, double d, SPtrB t, long l, SPtrB u, float f, SPtrB v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySPtrB(SPtrB s0, SPtrB s1, SPtrB s2, SPtrB s3, SPtrB s4, SPtrB s5, SPtrB s6, SPtrB s7, SPtrB s8, SPtrB s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SPtrB PickSPtrB(long which, SPtrB a, SPtrB b, SPtrB c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SFloat3 EchoSFloat3(SFloat3 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSFloat3(int a, SFloat3 s, double d, SFloat3 t, long l, SFloat3 u, float f, SFloat3 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySFloat3(SFloat3 s0, SFloat3 s1, SFloat3 s2, SFloat3 s3, SFloat3 s4, SFloat3 s5, SFloat3 s6, SFloat3 s7, SFloat3 s8, SFloat3 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SFloat3 PickSFloat3(long which, SFloat3 a, SFloat3 b, SFloat3 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SDoubleFloat EchoSDoubleFloat(SDoubleFloat s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSDoubleFloat(int a, SDoubleFloat s, double d, SDoubleFloat t, long l, SDoubleFloat u, float f, SDoubleFloat v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySDoubleFloat(SDoubleFloat s0, SDoubleFloat s1, SDoubleFloat s2, SDoubleFloat s3, SDoubleFloat s4, SDoubleFloat s5, SDoubleFloat s6, SDoubleFloat s7, SDoubleFloat s8, SDoubleFloat s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SDoubleFloat PickSDoubleFloat(long which, SDoubleFloat a, SDoubleFloat b, SDoubleFloat c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SByteFloat EchoSByteFloat(SByteFloat s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSByteFloat(int a, SByteFloat s, double d, SByteFloat t, long l, SByteFloat u, float f, SByteFloat v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySByteFloat(SByteFloat s0, SByteFloat s1, SByteFloat s2, SByteFloat s3, SByteFloat s4, SByteFloat s5, SByteFloat s6, SByteFloat s7, SByteFloat s8, SByteFloat s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SByteFloat PickSByteFloat(long which, SByteFloat a, SByteFloat b, SByteFloat c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SLongByte EchoSLongByte(SLongByte s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSLongByte(int a, SLongByte s, double d, SLongByte t, long l, SLongByte u, float f, SLongByte v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySLongByte(SLongByte s0, SLongByte s1, SLongByte s2, SLongByte s3, SLongByte s4, SLongByte s5, SLongByte s6, SLongByte s7, SLongByte s8, SLongByte s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SLongByte PickSLongByte(long which, SLongByte a, SLongByte b, SLongByte c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SFloatLong EchoSFloatLong(SFloatLong s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSFloatLong(int a, SFloatLong s, double d, SFloatLong t, long l, SFloatLong u, float f, SFloatLong v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySFloatLong(SFloatLong s0, SFloatLong s1, SFloatLong s2, SFloatLong s3, SFloatLong s4, SFloatLong s5, SFloatLong s6, SFloatLong s7, SFloatLong s8, SFloatLong s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SFloatLong PickSFloatLong(long which, SFloatLong a, SFloatLong b, SFloatLong c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SHalf3 EchoSHalf3(SHalf3 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSHalf3(int a, SHalf3 s, double d, SHalf3 t, long l, SHalf3 u, float f, SHalf3 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySHalf3(SHalf3 s0, SHalf3 s1, SHalf3 s2, SHalf3 s3, SHalf3 s4, SHalf3 s5, SHalf3 s6, SHalf3 s7, SHalf3 s8, SHalf3 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SHalf3 PickSHalf3(long which, SHalf3 a, SHalf3 b, SHalf3 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S40 EchoS40(S40 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixS40(int a, S40 s, double d, S40 t, long l, S40 u, float f, S40 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManyS40(S40 s0, S40 s1, S40 s2, S40 s3, S40 s4, S40 s5, S40 s6, S40 s7, S40 s8, S40 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static S40 PickS40(long which, S40 a, S40 b, S40 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SNested24 EchoSNested24(SNested24 s) => s;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long MixSNested24(int a, SNested24 s, double d, SNested24 t, long l, SNested24 u, float f, SNested24 v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long ManySNested24(SNested24 s0, SNested24 s1, SNested24 s2, SNested24 s3, SNested24 s4, SNested24 s5, SNested24 s6, SNested24 s7, SNested24 s8, SNested24 s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static SNested24 PickSNested24(long which, SNested24 a, SNested24 b, SNested24 c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;

    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long Scalars(sbyte a, byte b, short c, ushort d, int e, uint f, long g, ulong h, float i, double j, nint k, sbyte l, short m, float n, double o, byte p, double q, float r, long s, int t) =>
        unchecked(a + 3L * b + 5L * c + 7L * d + 11L * e + 13L * f + 17L * g + 19L * (long)h + 23L * BitConverter.SingleToInt32Bits(i) + 29L * BitConverter.DoubleToInt64Bits(j) + 31L * k + 37L * l + 41L * m + 43L * BitConverter.SingleToInt32Bits(n) + 47L * BitConverter.DoubleToInt64Bits(o) + 53L * p + 59L * BitConverter.DoubleToInt64Bits(q) + 61L * BitConverter.SingleToInt32Bits(r) + 67L * s + 71L * t);
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static sbyte RetSByte(int x) => (sbyte)x;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static byte RetByte(int x) => (byte)x;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static short RetShort(int x) => (short)x;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static ushort RetUShort(int x) => (ushort)x;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static float RetFloat(double x) => (float)x;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static Half RetHalf(float x) => (Half)x;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static int* EchoPtr(int* p) => p;
    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long Halves(Half a, Half b, Half c, Half d, Half e, Half f, Half g, Half h, Half i, Half j) =>
        unchecked(BitConverter.HalfToInt16Bits(a) + 3L * BitConverter.HalfToInt16Bits(b) + 5L * BitConverter.HalfToInt16Bits(c) + 7L * BitConverter.HalfToInt16Bits(d) + 11L * BitConverter.HalfToInt16Bits(e) + 13L * BitConverter.HalfToInt16Bits(f) + 17L * BitConverter.HalfToInt16Bits(g) + 19L * BitConverter.HalfToInt16Bits(h) + 23L * BitConverter.HalfToInt16Bits(i) + 29L * BitConverter.HalfToInt16Bits(j));

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
    public struct NonBlit { public int Key; [MarshalAs(UnmanagedType.U1)] public bool Flag; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 6)] public string Name; public double D; }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int StrLenCb([MarshalAs(UnmanagedType.LPUTF8Str)] string s);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int WStrLenCb([MarshalAs(UnmanagedType.LPWStr)] string s);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int AnsiStrLenCb([MarshalAs(UnmanagedType.LPStr)] string s);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long SumArrCb([In, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] int[] a, int n);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int FillArrCb([Out, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] int[] a, int n, int v);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long SumBytesCb([In, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] byte[] a, int n);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int BoolsCb([MarshalAs(UnmanagedType.U1)] bool a, [MarshalAs(UnmanagedType.Bool)] bool b, [MarshalAs(UnmanagedType.Bool)] bool c, [MarshalAs(UnmanagedType.I1)] bool d);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Unicode)] public delegate int CharsCb(char a, [MarshalAs(UnmanagedType.U1)] char b, [MarshalAs(UnmanagedType.U2)] char c);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long RefsCb(ref int x, out long y, in double z, ref NonBlit s);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long StructValCb(NonBlit s, int k);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] [return: MarshalAs(UnmanagedType.LPUTF8Str)] public delegate string RetStrCb(int n);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate S16 EchoS16Del(S16 s);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate S24 EchoS24Del(S24 s);
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long ScalarsDel(sbyte a, byte b, short c, ushort d, int e, uint f, long g, ulong h, float i, double j, nint k, sbyte l, short m, float n, double o, byte p, double q, float r, long s, int t);

    private static string s_lastString;
    private static int[] s_lastArray;
    private static readonly StrLenCb s_strLen = s => { s_lastString = s; return s?.Length ?? -1; };
    private static readonly WStrLenCb s_wstrLen = s => { s_lastString = s; return s?.Length ?? -1; };
    private static readonly AnsiStrLenCb s_ansiStrLen = s => { s_lastString = s; return s?.Length ?? -1; };
    private static readonly SumArrCb s_sumArr = (a, n) => { s_lastArray = a; long h = 0; foreach (int x in a ?? []) h = unchecked(h * 31 + x); return unchecked(h + (a?.Length ?? -1) * 1000003L); };
    private static readonly FillArrCb s_fillArr = (a, n, v) => { for (int i = 0; i < (a?.Length ?? 0); i++) a[i] = unchecked(v + i); return a?.Length ?? -1; };
    private static readonly SumBytesCb s_sumBytes = (a, n) => unchecked(Fold(a) + (a?.Length ?? -1) * 1000003L);
    private static readonly BoolsCb s_bools = (a, b, c, d) => (a ? 1 : 0) | (b ? 2 : 0) | (c ? 4 : 0) | (d ? 8 : 0);
    private static readonly CharsCb s_chars = (a, b, c) => a + 3 * b + 5 * c;
    private static readonly RefsCb s_refs = (ref int x, out long y, in double z, ref NonBlit s) => { long r = unchecked(x * 7L + BitConverter.DoubleToInt64Bits(z) + s.Key + (s.Flag ? 1 : 0) + (s.Name?.Length ?? -1)); x = unchecked(x + 1); y = r; s.Key = unchecked(s.Key * 2); s.Flag = !s.Flag; s.Name = "ok"; s.D = z; return r; };
    private static readonly StructValCb s_structVal = (s, k) => unchecked(s.Key + k * 1000003L + (s.Flag ? 1 : 0) + (s.Name?.Length ?? -1) * 7 + BitConverter.DoubleToInt64Bits(s.D));
    private static readonly RetStrCb s_retStr = n => n < 0 ? null : new string('x', n % 100) + n;

    public static void Run(ReadOnlySpan<byte> data)
    {
        var input = new FuzzInput(data);
        int which = input.Byte();
        switch (which % 32)
        {
            case 0: StructS4(ref input); break;
            case 1: StructS8(ref input); break;
            case 2: StructS8D(ref input); break;
            case 3: StructS12(ref input); break;
            case 4: StructS16(ref input); break;
            case 5: StructS16D(ref input); break;
            case 6: StructS16F(ref input); break;
            case 7: StructS20(ref input); break;
            case 8: StructS24(ref input); break;
            case 9: StructS32(ref input); break;
            case 10: StructS3(ref input); break;
            case 11: StructS6(ref input); break;
            case 12: StructS7(ref input); break;
            case 13: StructS9(ref input); break;
            case 14: StructSFI(ref input); break;
            case 15: StructSDI(ref input); break;
            case 16: StructSNested(ref input); break;
            case 17: StructSHalf(ref input); break;
            case 18: StructSGuid(ref input); break;
            case 19: StructSPtrB(ref input); break;
            case 20: StructSFloat3(ref input); break;
            case 21: StructSDoubleFloat(ref input); break;
            case 22: StructSByteFloat(ref input); break;
            case 23: StructSLongByte(ref input); break;
            case 24: StructSFloatLong(ref input); break;
            case 25: StructSHalf3(ref input); break;
            case 26: StructS40(ref input); break;
            case 27: StructSNested24(ref input); break;
            case 28: ScalarCases(ref input); break;
            case 29: DelegateCases(ref input); break;
            case 30: ReverseStrings(ref input); break;
            default: ReverseValues(ref input); break;
        }
    }

    private static void StructS4(ref FuzzInput input)
    {
        S4 a = Read<S4>(ref input), b = Read<S4>(ref input), c = Read<S4>(ref input), d = Read<S4>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S4, S4> echo = &EchoS4;
        Check.Equal(Fold(a), Fold(echo(a)), "S4 echo");
        delegate* unmanaged[Cdecl]<int, S4, double, S4, long, S4, float, S4, long> mix = &MixS4;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S4 mix");
        delegate* unmanaged[Cdecl]<S4, S4, S4, S4, S4, S4, S4, S4, S4, S4, long, long> many = &ManyS4;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S4 many");
        delegate* unmanaged[Cdecl]<long, S4, S4, S4, S4> pick = &PickS4;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S4 pick");
    }

    private static void StructS8(ref FuzzInput input)
    {
        S8 a = Read<S8>(ref input), b = Read<S8>(ref input), c = Read<S8>(ref input), d = Read<S8>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S8, S8> echo = &EchoS8;
        Check.Equal(Fold(a), Fold(echo(a)), "S8 echo");
        delegate* unmanaged[Cdecl]<int, S8, double, S8, long, S8, float, S8, long> mix = &MixS8;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S8 mix");
        delegate* unmanaged[Cdecl]<S8, S8, S8, S8, S8, S8, S8, S8, S8, S8, long, long> many = &ManyS8;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S8 many");
        delegate* unmanaged[Cdecl]<long, S8, S8, S8, S8> pick = &PickS8;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S8 pick");
    }

    private static void StructS8D(ref FuzzInput input)
    {
        S8D a = Read<S8D>(ref input), b = Read<S8D>(ref input), c = Read<S8D>(ref input), d = Read<S8D>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S8D, S8D> echo = &EchoS8D;
        Check.Equal(Fold(a), Fold(echo(a)), "S8D echo");
        delegate* unmanaged[Cdecl]<int, S8D, double, S8D, long, S8D, float, S8D, long> mix = &MixS8D;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S8D mix");
        delegate* unmanaged[Cdecl]<S8D, S8D, S8D, S8D, S8D, S8D, S8D, S8D, S8D, S8D, long, long> many = &ManyS8D;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S8D many");
        delegate* unmanaged[Cdecl]<long, S8D, S8D, S8D, S8D> pick = &PickS8D;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S8D pick");
    }

    private static void StructS12(ref FuzzInput input)
    {
        S12 a = Read<S12>(ref input), b = Read<S12>(ref input), c = Read<S12>(ref input), d = Read<S12>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S12, S12> echo = &EchoS12;
        Check.Equal(Fold(a), Fold(echo(a)), "S12 echo");
        delegate* unmanaged[Cdecl]<int, S12, double, S12, long, S12, float, S12, long> mix = &MixS12;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S12 mix");
        delegate* unmanaged[Cdecl]<S12, S12, S12, S12, S12, S12, S12, S12, S12, S12, long, long> many = &ManyS12;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S12 many");
        delegate* unmanaged[Cdecl]<long, S12, S12, S12, S12> pick = &PickS12;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S12 pick");
    }

    private static void StructS16(ref FuzzInput input)
    {
        S16 a = Read<S16>(ref input), b = Read<S16>(ref input), c = Read<S16>(ref input), d = Read<S16>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S16, S16> echo = &EchoS16;
        Check.Equal(Fold(a), Fold(echo(a)), "S16 echo");
        delegate* unmanaged[Cdecl]<int, S16, double, S16, long, S16, float, S16, long> mix = &MixS16;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S16 mix");
        delegate* unmanaged[Cdecl]<S16, S16, S16, S16, S16, S16, S16, S16, S16, S16, long, long> many = &ManyS16;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S16 many");
        delegate* unmanaged[Cdecl]<long, S16, S16, S16, S16> pick = &PickS16;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S16 pick");
    }

    private static void StructS16D(ref FuzzInput input)
    {
        S16D a = Read<S16D>(ref input), b = Read<S16D>(ref input), c = Read<S16D>(ref input), d = Read<S16D>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S16D, S16D> echo = &EchoS16D;
        Check.Equal(Fold(a), Fold(echo(a)), "S16D echo");
        delegate* unmanaged[Cdecl]<int, S16D, double, S16D, long, S16D, float, S16D, long> mix = &MixS16D;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S16D mix");
        delegate* unmanaged[Cdecl]<S16D, S16D, S16D, S16D, S16D, S16D, S16D, S16D, S16D, S16D, long, long> many = &ManyS16D;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S16D many");
        delegate* unmanaged[Cdecl]<long, S16D, S16D, S16D, S16D> pick = &PickS16D;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S16D pick");
    }

    private static void StructS16F(ref FuzzInput input)
    {
        S16F a = Read<S16F>(ref input), b = Read<S16F>(ref input), c = Read<S16F>(ref input), d = Read<S16F>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S16F, S16F> echo = &EchoS16F;
        Check.Equal(Fold(a), Fold(echo(a)), "S16F echo");
        delegate* unmanaged[Cdecl]<int, S16F, double, S16F, long, S16F, float, S16F, long> mix = &MixS16F;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S16F mix");
        delegate* unmanaged[Cdecl]<S16F, S16F, S16F, S16F, S16F, S16F, S16F, S16F, S16F, S16F, long, long> many = &ManyS16F;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S16F many");
        delegate* unmanaged[Cdecl]<long, S16F, S16F, S16F, S16F> pick = &PickS16F;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S16F pick");
    }

    private static void StructS20(ref FuzzInput input)
    {
        S20 a = Read<S20>(ref input), b = Read<S20>(ref input), c = Read<S20>(ref input), d = Read<S20>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S20, S20> echo = &EchoS20;
        Check.Equal(Fold(a), Fold(echo(a)), "S20 echo");
        delegate* unmanaged[Cdecl]<int, S20, double, S20, long, S20, float, S20, long> mix = &MixS20;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S20 mix");
        delegate* unmanaged[Cdecl]<S20, S20, S20, S20, S20, S20, S20, S20, S20, S20, long, long> many = &ManyS20;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S20 many");
        delegate* unmanaged[Cdecl]<long, S20, S20, S20, S20> pick = &PickS20;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S20 pick");
    }

    private static void StructS24(ref FuzzInput input)
    {
        S24 a = Read<S24>(ref input), b = Read<S24>(ref input), c = Read<S24>(ref input), d = Read<S24>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S24, S24> echo = &EchoS24;
        Check.Equal(Fold(a), Fold(echo(a)), "S24 echo");
        delegate* unmanaged[Cdecl]<int, S24, double, S24, long, S24, float, S24, long> mix = &MixS24;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S24 mix");
        delegate* unmanaged[Cdecl]<S24, S24, S24, S24, S24, S24, S24, S24, S24, S24, long, long> many = &ManyS24;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S24 many");
        delegate* unmanaged[Cdecl]<long, S24, S24, S24, S24> pick = &PickS24;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S24 pick");
    }

    private static void StructS32(ref FuzzInput input)
    {
        S32 a = Read<S32>(ref input), b = Read<S32>(ref input), c = Read<S32>(ref input), d = Read<S32>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S32, S32> echo = &EchoS32;
        Check.Equal(Fold(a), Fold(echo(a)), "S32 echo");
        delegate* unmanaged[Cdecl]<int, S32, double, S32, long, S32, float, S32, long> mix = &MixS32;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S32 mix");
        delegate* unmanaged[Cdecl]<S32, S32, S32, S32, S32, S32, S32, S32, S32, S32, long, long> many = &ManyS32;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S32 many");
        delegate* unmanaged[Cdecl]<long, S32, S32, S32, S32> pick = &PickS32;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S32 pick");
    }

    private static void StructS3(ref FuzzInput input)
    {
        S3 a = Read<S3>(ref input), b = Read<S3>(ref input), c = Read<S3>(ref input), d = Read<S3>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S3, S3> echo = &EchoS3;
        Check.Equal(Fold(a), Fold(echo(a)), "S3 echo");
        delegate* unmanaged[Cdecl]<int, S3, double, S3, long, S3, float, S3, long> mix = &MixS3;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S3 mix");
        delegate* unmanaged[Cdecl]<S3, S3, S3, S3, S3, S3, S3, S3, S3, S3, long, long> many = &ManyS3;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S3 many");
        delegate* unmanaged[Cdecl]<long, S3, S3, S3, S3> pick = &PickS3;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S3 pick");
    }

    private static void StructS6(ref FuzzInput input)
    {
        S6 a = Read<S6>(ref input), b = Read<S6>(ref input), c = Read<S6>(ref input), d = Read<S6>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S6, S6> echo = &EchoS6;
        Check.Equal(Fold(a), Fold(echo(a)), "S6 echo");
        delegate* unmanaged[Cdecl]<int, S6, double, S6, long, S6, float, S6, long> mix = &MixS6;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S6 mix");
        delegate* unmanaged[Cdecl]<S6, S6, S6, S6, S6, S6, S6, S6, S6, S6, long, long> many = &ManyS6;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S6 many");
        delegate* unmanaged[Cdecl]<long, S6, S6, S6, S6> pick = &PickS6;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S6 pick");
    }

    private static void StructS7(ref FuzzInput input)
    {
        S7 a = Read<S7>(ref input), b = Read<S7>(ref input), c = Read<S7>(ref input), d = Read<S7>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S7, S7> echo = &EchoS7;
        Check.Equal(Fold(a), Fold(echo(a)), "S7 echo");
        delegate* unmanaged[Cdecl]<int, S7, double, S7, long, S7, float, S7, long> mix = &MixS7;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S7 mix");
        delegate* unmanaged[Cdecl]<S7, S7, S7, S7, S7, S7, S7, S7, S7, S7, long, long> many = &ManyS7;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S7 many");
        delegate* unmanaged[Cdecl]<long, S7, S7, S7, S7> pick = &PickS7;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S7 pick");
    }

    private static void StructS9(ref FuzzInput input)
    {
        S9 a = Read<S9>(ref input), b = Read<S9>(ref input), c = Read<S9>(ref input), d = Read<S9>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S9, S9> echo = &EchoS9;
        Check.Equal(Fold(a), Fold(echo(a)), "S9 echo");
        delegate* unmanaged[Cdecl]<int, S9, double, S9, long, S9, float, S9, long> mix = &MixS9;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S9 mix");
        delegate* unmanaged[Cdecl]<S9, S9, S9, S9, S9, S9, S9, S9, S9, S9, long, long> many = &ManyS9;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S9 many");
        delegate* unmanaged[Cdecl]<long, S9, S9, S9, S9> pick = &PickS9;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S9 pick");
    }

    private static void StructSFI(ref FuzzInput input)
    {
        SFI a = Read<SFI>(ref input), b = Read<SFI>(ref input), c = Read<SFI>(ref input), d = Read<SFI>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SFI, SFI> echo = &EchoSFI;
        Check.Equal(Fold(a), Fold(echo(a)), "SFI echo");
        delegate* unmanaged[Cdecl]<int, SFI, double, SFI, long, SFI, float, SFI, long> mix = &MixSFI;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SFI mix");
        delegate* unmanaged[Cdecl]<SFI, SFI, SFI, SFI, SFI, SFI, SFI, SFI, SFI, SFI, long, long> many = &ManySFI;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SFI many");
        delegate* unmanaged[Cdecl]<long, SFI, SFI, SFI, SFI> pick = &PickSFI;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SFI pick");
    }

    private static void StructSDI(ref FuzzInput input)
    {
        SDI a = Read<SDI>(ref input), b = Read<SDI>(ref input), c = Read<SDI>(ref input), d = Read<SDI>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SDI, SDI> echo = &EchoSDI;
        Check.Equal(Fold(a), Fold(echo(a)), "SDI echo");
        delegate* unmanaged[Cdecl]<int, SDI, double, SDI, long, SDI, float, SDI, long> mix = &MixSDI;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SDI mix");
        delegate* unmanaged[Cdecl]<SDI, SDI, SDI, SDI, SDI, SDI, SDI, SDI, SDI, SDI, long, long> many = &ManySDI;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SDI many");
        delegate* unmanaged[Cdecl]<long, SDI, SDI, SDI, SDI> pick = &PickSDI;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SDI pick");
    }

    private static void StructSNested(ref FuzzInput input)
    {
        SNested a = Read<SNested>(ref input), b = Read<SNested>(ref input), c = Read<SNested>(ref input), d = Read<SNested>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SNested, SNested> echo = &EchoSNested;
        Check.Equal(Fold(a), Fold(echo(a)), "SNested echo");
        delegate* unmanaged[Cdecl]<int, SNested, double, SNested, long, SNested, float, SNested, long> mix = &MixSNested;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SNested mix");
        delegate* unmanaged[Cdecl]<SNested, SNested, SNested, SNested, SNested, SNested, SNested, SNested, SNested, SNested, long, long> many = &ManySNested;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SNested many");
        delegate* unmanaged[Cdecl]<long, SNested, SNested, SNested, SNested> pick = &PickSNested;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SNested pick");
    }

    private static void StructSHalf(ref FuzzInput input)
    {
        SHalf a = Read<SHalf>(ref input), b = Read<SHalf>(ref input), c = Read<SHalf>(ref input), d = Read<SHalf>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SHalf, SHalf> echo = &EchoSHalf;
        Check.Equal(Fold(a), Fold(echo(a)), "SHalf echo");
        delegate* unmanaged[Cdecl]<int, SHalf, double, SHalf, long, SHalf, float, SHalf, long> mix = &MixSHalf;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SHalf mix");
        delegate* unmanaged[Cdecl]<SHalf, SHalf, SHalf, SHalf, SHalf, SHalf, SHalf, SHalf, SHalf, SHalf, long, long> many = &ManySHalf;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SHalf many");
        delegate* unmanaged[Cdecl]<long, SHalf, SHalf, SHalf, SHalf> pick = &PickSHalf;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SHalf pick");
    }

    private static void StructSGuid(ref FuzzInput input)
    {
        SGuid a = Read<SGuid>(ref input), b = Read<SGuid>(ref input), c = Read<SGuid>(ref input), d = Read<SGuid>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SGuid, SGuid> echo = &EchoSGuid;
        Check.Equal(Fold(a), Fold(echo(a)), "SGuid echo");
        delegate* unmanaged[Cdecl]<int, SGuid, double, SGuid, long, SGuid, float, SGuid, long> mix = &MixSGuid;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SGuid mix");
        delegate* unmanaged[Cdecl]<SGuid, SGuid, SGuid, SGuid, SGuid, SGuid, SGuid, SGuid, SGuid, SGuid, long, long> many = &ManySGuid;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SGuid many");
        delegate* unmanaged[Cdecl]<long, SGuid, SGuid, SGuid, SGuid> pick = &PickSGuid;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SGuid pick");
    }

    private static void StructSPtrB(ref FuzzInput input)
    {
        SPtrB a = Read<SPtrB>(ref input), b = Read<SPtrB>(ref input), c = Read<SPtrB>(ref input), d = Read<SPtrB>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SPtrB, SPtrB> echo = &EchoSPtrB;
        Check.Equal(Fold(a), Fold(echo(a)), "SPtrB echo");
        delegate* unmanaged[Cdecl]<int, SPtrB, double, SPtrB, long, SPtrB, float, SPtrB, long> mix = &MixSPtrB;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SPtrB mix");
        delegate* unmanaged[Cdecl]<SPtrB, SPtrB, SPtrB, SPtrB, SPtrB, SPtrB, SPtrB, SPtrB, SPtrB, SPtrB, long, long> many = &ManySPtrB;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SPtrB many");
        delegate* unmanaged[Cdecl]<long, SPtrB, SPtrB, SPtrB, SPtrB> pick = &PickSPtrB;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SPtrB pick");
    }

    private static void StructSFloat3(ref FuzzInput input)
    {
        SFloat3 a = Read<SFloat3>(ref input), b = Read<SFloat3>(ref input), c = Read<SFloat3>(ref input), d = Read<SFloat3>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SFloat3, SFloat3> echo = &EchoSFloat3;
        Check.Equal(Fold(a), Fold(echo(a)), "SFloat3 echo");
        delegate* unmanaged[Cdecl]<int, SFloat3, double, SFloat3, long, SFloat3, float, SFloat3, long> mix = &MixSFloat3;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SFloat3 mix");
        delegate* unmanaged[Cdecl]<SFloat3, SFloat3, SFloat3, SFloat3, SFloat3, SFloat3, SFloat3, SFloat3, SFloat3, SFloat3, long, long> many = &ManySFloat3;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SFloat3 many");
        delegate* unmanaged[Cdecl]<long, SFloat3, SFloat3, SFloat3, SFloat3> pick = &PickSFloat3;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SFloat3 pick");
    }

    private static void StructSDoubleFloat(ref FuzzInput input)
    {
        SDoubleFloat a = Read<SDoubleFloat>(ref input), b = Read<SDoubleFloat>(ref input), c = Read<SDoubleFloat>(ref input), d = Read<SDoubleFloat>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SDoubleFloat, SDoubleFloat> echo = &EchoSDoubleFloat;
        Check.Equal(Fold(a), Fold(echo(a)), "SDoubleFloat echo");
        delegate* unmanaged[Cdecl]<int, SDoubleFloat, double, SDoubleFloat, long, SDoubleFloat, float, SDoubleFloat, long> mix = &MixSDoubleFloat;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SDoubleFloat mix");
        delegate* unmanaged[Cdecl]<SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat, long, long> many = &ManySDoubleFloat;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SDoubleFloat many");
        delegate* unmanaged[Cdecl]<long, SDoubleFloat, SDoubleFloat, SDoubleFloat, SDoubleFloat> pick = &PickSDoubleFloat;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SDoubleFloat pick");
    }

    private static void StructSByteFloat(ref FuzzInput input)
    {
        SByteFloat a = Read<SByteFloat>(ref input), b = Read<SByteFloat>(ref input), c = Read<SByteFloat>(ref input), d = Read<SByteFloat>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SByteFloat, SByteFloat> echo = &EchoSByteFloat;
        Check.Equal(Fold(a), Fold(echo(a)), "SByteFloat echo");
        delegate* unmanaged[Cdecl]<int, SByteFloat, double, SByteFloat, long, SByteFloat, float, SByteFloat, long> mix = &MixSByteFloat;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SByteFloat mix");
        delegate* unmanaged[Cdecl]<SByteFloat, SByteFloat, SByteFloat, SByteFloat, SByteFloat, SByteFloat, SByteFloat, SByteFloat, SByteFloat, SByteFloat, long, long> many = &ManySByteFloat;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SByteFloat many");
        delegate* unmanaged[Cdecl]<long, SByteFloat, SByteFloat, SByteFloat, SByteFloat> pick = &PickSByteFloat;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SByteFloat pick");
    }

    private static void StructSLongByte(ref FuzzInput input)
    {
        SLongByte a = Read<SLongByte>(ref input), b = Read<SLongByte>(ref input), c = Read<SLongByte>(ref input), d = Read<SLongByte>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SLongByte, SLongByte> echo = &EchoSLongByte;
        Check.Equal(Fold(a), Fold(echo(a)), "SLongByte echo");
        delegate* unmanaged[Cdecl]<int, SLongByte, double, SLongByte, long, SLongByte, float, SLongByte, long> mix = &MixSLongByte;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SLongByte mix");
        delegate* unmanaged[Cdecl]<SLongByte, SLongByte, SLongByte, SLongByte, SLongByte, SLongByte, SLongByte, SLongByte, SLongByte, SLongByte, long, long> many = &ManySLongByte;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SLongByte many");
        delegate* unmanaged[Cdecl]<long, SLongByte, SLongByte, SLongByte, SLongByte> pick = &PickSLongByte;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SLongByte pick");
    }

    private static void StructSFloatLong(ref FuzzInput input)
    {
        SFloatLong a = Read<SFloatLong>(ref input), b = Read<SFloatLong>(ref input), c = Read<SFloatLong>(ref input), d = Read<SFloatLong>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SFloatLong, SFloatLong> echo = &EchoSFloatLong;
        Check.Equal(Fold(a), Fold(echo(a)), "SFloatLong echo");
        delegate* unmanaged[Cdecl]<int, SFloatLong, double, SFloatLong, long, SFloatLong, float, SFloatLong, long> mix = &MixSFloatLong;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SFloatLong mix");
        delegate* unmanaged[Cdecl]<SFloatLong, SFloatLong, SFloatLong, SFloatLong, SFloatLong, SFloatLong, SFloatLong, SFloatLong, SFloatLong, SFloatLong, long, long> many = &ManySFloatLong;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SFloatLong many");
        delegate* unmanaged[Cdecl]<long, SFloatLong, SFloatLong, SFloatLong, SFloatLong> pick = &PickSFloatLong;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SFloatLong pick");
    }

    private static void StructSHalf3(ref FuzzInput input)
    {
        SHalf3 a = Read<SHalf3>(ref input), b = Read<SHalf3>(ref input), c = Read<SHalf3>(ref input), d = Read<SHalf3>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SHalf3, SHalf3> echo = &EchoSHalf3;
        Check.Equal(Fold(a), Fold(echo(a)), "SHalf3 echo");
        delegate* unmanaged[Cdecl]<int, SHalf3, double, SHalf3, long, SHalf3, float, SHalf3, long> mix = &MixSHalf3;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SHalf3 mix");
        delegate* unmanaged[Cdecl]<SHalf3, SHalf3, SHalf3, SHalf3, SHalf3, SHalf3, SHalf3, SHalf3, SHalf3, SHalf3, long, long> many = &ManySHalf3;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SHalf3 many");
        delegate* unmanaged[Cdecl]<long, SHalf3, SHalf3, SHalf3, SHalf3> pick = &PickSHalf3;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SHalf3 pick");
    }

    private static void StructS40(ref FuzzInput input)
    {
        S40 a = Read<S40>(ref input), b = Read<S40>(ref input), c = Read<S40>(ref input), d = Read<S40>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<S40, S40> echo = &EchoS40;
        Check.Equal(Fold(a), Fold(echo(a)), "S40 echo");
        delegate* unmanaged[Cdecl]<int, S40, double, S40, long, S40, float, S40, long> mix = &MixS40;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "S40 mix");
        delegate* unmanaged[Cdecl]<S40, S40, S40, S40, S40, S40, S40, S40, S40, S40, long, long> many = &ManyS40;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "S40 many");
        delegate* unmanaged[Cdecl]<long, S40, S40, S40, S40> pick = &PickS40;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "S40 pick");
    }

    private static void StructSNested24(ref FuzzInput input)
    {
        SNested24 a = Read<SNested24>(ref input), b = Read<SNested24>(ref input), c = Read<SNested24>(ref input), d = Read<SNested24>(ref input);
        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());
        delegate* unmanaged[Cdecl]<SNested24, SNested24> echo = &EchoSNested24;
        Check.Equal(Fold(a), Fold(echo(a)), "SNested24 echo");
        delegate* unmanaged[Cdecl]<int, SNested24, double, SNested24, long, SNested24, float, SNested24, long> mix = &MixSNested24;
        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), "SNested24 mix");
        delegate* unmanaged[Cdecl]<SNested24, SNested24, SNested24, SNested24, SNested24, SNested24, SNested24, SNested24, SNested24, SNested24, long, long> many = &ManySNested24;
        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), "SNested24 many");
        delegate* unmanaged[Cdecl]<long, SNested24, SNested24, SNested24, SNested24> pick = &PickSNested24;
        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), "SNested24 pick");
    }

    private static void ScalarCases(ref FuzzInput input)
    {
        sbyte a = (sbyte)input.Byte(); byte b = input.Byte(); short c = (short)input.UInt16(); ushort d = input.UInt16(); int e = input.Int32(); uint f = (uint)input.Int32();
        long g = (long)input.Int32() << 32 | (uint)input.Int32(); ulong h = (ulong)input.Int32() << 32 | (uint)input.Int32(); float i = BitConverter.Int32BitsToSingle(input.Int32()); double j = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32());
        nint k = (nint)input.Int32(); sbyte l = (sbyte)input.Byte(); short m = (short)input.UInt16(); float n = BitConverter.Int32BitsToSingle(input.Int32()); double o = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32());
        byte p = input.Byte(); double q = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float r = BitConverter.Int32BitsToSingle(input.Int32()); long s = (long)input.Int32() << 32 | (uint)input.Int32(); int t = input.Int32();
        long expected = unchecked(a + 3L * b + 5L * c + 7L * d + 11L * e + 13L * f + 17L * g + 19L * (long)h + 23L * BitConverter.SingleToInt32Bits(i) + 29L * BitConverter.DoubleToInt64Bits(j) + 31L * k + 37L * l + 41L * m + 43L * BitConverter.SingleToInt32Bits(n) + 47L * BitConverter.DoubleToInt64Bits(o) + 53L * p + 59L * BitConverter.DoubleToInt64Bits(q) + 61L * BitConverter.SingleToInt32Bits(r) + 67L * s + 71L * t);
        delegate* unmanaged[Cdecl]<sbyte, byte, short, ushort, int, uint, long, ulong, float, double, nint, sbyte, short, float, double, byte, double, float, long, int, long> scalars = &Scalars;
        Check.Equal(expected, scalars(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t), "scalars");
        var scalarsDel = Marshal.GetDelegateForFunctionPointer<ScalarsDel>((IntPtr)scalars);
        Check.Equal(expected, scalarsDel(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t), "scalars through a delegate");
        delegate* unmanaged[Cdecl]<int, sbyte> retSByte = &RetSByte; Check.Equal((sbyte)e, retSByte(e), "sbyte return");
        delegate* unmanaged[Cdecl]<int, byte> retByte = &RetByte; Check.Equal((byte)e, retByte(e), "byte return");
        delegate* unmanaged[Cdecl]<int, short> retShort = &RetShort; Check.Equal((short)e, retShort(e), "short return");
        delegate* unmanaged[Cdecl]<int, ushort> retUShort = &RetUShort; Check.Equal((ushort)e, retUShort(e), "ushort return");
        delegate* unmanaged[Cdecl]<double, float> retFloat = &RetFloat; Check.Equal(BitConverter.SingleToInt32Bits((float)j), BitConverter.SingleToInt32Bits(retFloat(j)), "float return");
        delegate* unmanaged[Cdecl]<float, Half> retHalf = &RetHalf; Check.Equal(BitConverter.HalfToInt16Bits((Half)i), BitConverter.HalfToInt16Bits(retHalf(i)), "Half return");
        int local = e; delegate* unmanaged[Cdecl]<int*, int*> echoPtr = &EchoPtr; Check.That(echoPtr(&local) == &local, "pointer echo");
        delegate* unmanaged[Cdecl]<Half, Half, Half, Half, Half, Half, Half, Half, Half, Half, long> halves = &Halves;
        Half h0 = (Half)i, h1 = (Half)j, h2 = (Half)n, h3 = (Half)o, h4 = (Half)q, h5 = (Half)r, h6 = BitConverter.Int16BitsToHalf(c), h7 = BitConverter.Int16BitsToHalf((short)d), h8 = BitConverter.Int16BitsToHalf(m), h9 = BitConverter.Int16BitsToHalf((short)e);
        Check.Equal(unchecked(BitConverter.HalfToInt16Bits(h0) + 3L * BitConverter.HalfToInt16Bits(h1) + 5L * BitConverter.HalfToInt16Bits(h2) + 7L * BitConverter.HalfToInt16Bits(h3) + 11L * BitConverter.HalfToInt16Bits(h4) + 13L * BitConverter.HalfToInt16Bits(h5) + 17L * BitConverter.HalfToInt16Bits(h6) + 19L * BitConverter.HalfToInt16Bits(h7) + 23L * BitConverter.HalfToInt16Bits(h8) + 29L * BitConverter.HalfToInt16Bits(h9)), halves(h0, h1, h2, h3, h4, h5, h6, h7, h8, h9), "ten Halves");
    }

    private static void DelegateCases(ref FuzzInput input)
    {
        S16 a = Read<S16>(ref input); S24 b = Read<S24>(ref input);
        delegate* unmanaged[Cdecl]<S16, S16> e16 = &EchoS16; delegate* unmanaged[Cdecl]<S24, S24> e24 = &EchoS24;
        var d16 = Marshal.GetDelegateForFunctionPointer<EchoS16Del>((IntPtr)e16); var d24 = Marshal.GetDelegateForFunctionPointer<EchoS24Del>((IntPtr)e24);
        Check.Equal(Fold(a), Fold(d16(a)), "S16 echo through a delegate"); Check.Equal(Fold(b), Fold(d24(b)), "S24 echo through a delegate");
        // A managed delegate exposed as a function pointer and called through it: the reverse thunk for blittable structs.
        EchoS16Del m16 = s => new S16 { A = s.A + 1, B = s.B * 2 }; EchoS24Del m24 = s => new S24 { A = s.C, B = s.B, C = s.A };
        var f16 = (delegate* unmanaged[Cdecl]<S16, S16>)Marshal.GetFunctionPointerForDelegate(m16); var f24 = (delegate* unmanaged[Cdecl]<S24, S24>)Marshal.GetFunctionPointerForDelegate(m24);
        S16 r16 = f16(a); S24 r24 = f24(b);
        Check.That(r16.A == a.A + 1 && BitConverter.DoubleToInt64Bits(r16.B) == BitConverter.DoubleToInt64Bits(a.B * 2), "S16 through a delegate thunk");
        Check.That(r24.A == b.C && BitConverter.DoubleToInt64Bits(r24.B) == BitConverter.DoubleToInt64Bits(b.B) && r24.C == b.A, "S24 through a delegate thunk");
        GC.KeepAlive(m16); GC.KeepAlive(m24);
    }

    /// <summary>Delegate thunks whose reverse stubs marshal strings and arrays from guarded native memory.</summary>
    private static void ReverseStrings(ref FuzzInput input)
    {
        byte flags = input.Byte();
        byte[] text = input.SegmentBytes().ToArray();
        int[] ints = MemoryMarshal.Cast<byte, int>(input.Bytes(Math.Min(input.Remaining, 64))).ToArray();
        bool atStart = (flags & 1) != 0;
        // UTF-8, NUL last before the guard page.
        byte* utf8 = Guarded.Allocate(text.Length + 1, atStart);
        text.CopyTo(new Span<byte>(utf8, text.Length)); utf8[text.Length] = 0;
        string expected = Encoding.UTF8.GetString(text);
        var strLen = (delegate* unmanaged[Cdecl]<byte*, int>)Marshal.GetFunctionPointerForDelegate(s_strLen);
        Check.Equal(expected.Length, strLen(utf8), "LPUTF8Str callback length"); Check.Equal(expected, s_lastString, "LPUTF8Str callback string");
        Check.Equal(-1, strLen(null), "LPUTF8Str callback null");
        var ansiLen = (delegate* unmanaged[Cdecl]<byte*, int>)Marshal.GetFunctionPointerForDelegate(s_ansiStrLen);
        Check.Equal(expected.Length, ansiLen(utf8), "LPStr callback length"); Check.Equal(expected, s_lastString, "LPStr callback string");
        // UTF-16, NUL char last.
        char[] wide = Encoding.Unicode.GetString(text, 0, text.Length & ~1).ToCharArray();
        int nul = Array.IndexOf(wide, '\0'); if (nul >= 0) wide = wide.AsSpan(0, nul).ToArray();
        char* utf16 = (char*)Guarded.Allocate((wide.Length + 1) * 2L, !atStart);
        wide.CopyTo(new Span<char>(utf16, wide.Length)); utf16[wide.Length] = '\0';
        var wstrLen = (delegate* unmanaged[Cdecl]<char*, int>)Marshal.GetFunctionPointerForDelegate(s_wstrLen);
        Check.Equal(wide.Length, wstrLen(utf16), "LPWStr callback length"); Check.Equal(new string(wide), s_lastString, "LPWStr callback string");
        // [In] int[] with SizeParamIndex from exactly n guarded ints; [Out] int[] written back into exactly n guarded ints.
        int* nativeInts = (int*)Guarded.Allocate(ints.Length * 4L, atStart);
        ints.CopyTo(new Span<int>(nativeInts, ints.Length));
        var sumArr = (delegate* unmanaged[Cdecl]<int*, int, long>)Marshal.GetFunctionPointerForDelegate(s_sumArr);
        long h = 0; foreach (int x in ints) h = unchecked(h * 31 + x);
        Check.Equal(unchecked(h + ints.Length * 1000003L), sumArr(nativeInts, ints.Length), "[In] int[] callback");
        Check.That(s_lastArray is not null && s_lastArray.SequenceEqual(ints), "[In] int[] callback contents");
        Check.Equal(-1000003L, sumArr(null, 3), "[In] int[] callback null");
        var fillArr = (delegate* unmanaged[Cdecl]<int*, int, int, int>)Marshal.GetFunctionPointerForDelegate(s_fillArr);
        int v = flags * 1000;
        Check.Equal(ints.Length, fillArr(nativeInts, ints.Length, v), "[Out] int[] callback");
        for (int i = 0; i < ints.Length; i++) Check.Equal(unchecked(v + i), nativeInts[i], $"[Out] int[] callback element {i}");
        var sumBytes = (delegate* unmanaged[Cdecl]<byte*, int, long>)Marshal.GetFunctionPointerForDelegate(s_sumBytes);
        Check.Equal(unchecked(Fold(text) + text.Length * 1000003L), sumBytes(utf8, text.Length), "[In] byte[] callback");
        // A string returned from a callback is a CoTaskMem UTF-8 copy the caller owns.
        var retStr = (delegate* unmanaged[Cdecl]<int, byte*>)Marshal.GetFunctionPointerForDelegate(s_retStr);
        int n = ints.Length > 0 ? ints[0] : flags;
        byte* ret = retStr(n);
        if (n < 0) Check.That(ret == null, "null string return");
        else { Check.Equal(new string('x', n % 100) + n, Marshal.PtrToStringUTF8((IntPtr)ret), "string return"); Marshal.FreeCoTaskMem((IntPtr)ret); }
        GC.KeepAlive(s_strLen); GC.KeepAlive(s_wstrLen); GC.KeepAlive(s_ansiStrLen); GC.KeepAlive(s_sumArr); GC.KeepAlive(s_fillArr); GC.KeepAlive(s_sumBytes); GC.KeepAlive(s_retStr);
    }

    /// <summary>Delegate thunks marshalling bools, chars, by-ref values and non-blittable structs.</summary>
    private static void ReverseValues(ref FuzzInput input)
    {
        byte ba = input.Byte(); int bb = input.Int32(); int bc = input.Int32(); byte bd = input.Byte();
        var bools = (delegate* unmanaged[Cdecl]<byte, int, int, sbyte, int>)Marshal.GetFunctionPointerForDelegate(s_bools);
        Check.Equal((ba != 0 ? 1 : 0) | (bb != 0 ? 2 : 0) | (bc != 0 ? 4 : 0) | (bd != 0 ? 8 : 0), bools(ba, bb, bc, (sbyte)bd), "bool callback");
        // char in an unmanaged function pointer signature would be marshalled as ANSI by the caller, so the raw UTF-16 units go through ushort.
        ushort ca = input.UInt16(); byte cb = (byte)(input.Byte() & 0x7F); ushort cc = input.UInt16();
        var chars = (delegate* unmanaged[Cdecl]<ushort, byte, ushort, int>)Marshal.GetFunctionPointerForDelegate(s_chars);
        Check.Equal(ca + 3 * cb + 5 * cc, chars(ca, cb, cc), "char callback");
        int x = input.Int32(); double z = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32());
        var rec = new NonBlit { Key = input.Int32(), Flag = (input.Byte() & 1) != 0, Name = new string((char)('a' + input.Byte() % 26), input.Byte() % 6), D = z };
        int size = Marshal.SizeOf<NonBlit>();
        byte* native = Guarded.Allocate(size, (x & 1) != 0);
        Marshal.StructureToPtr(rec, (IntPtr)native, false);
        int nx = x; long ny = 0;
        var refs = (delegate* unmanaged[Cdecl]<int*, long*, double*, byte*, long>)Marshal.GetFunctionPointerForDelegate(s_refs);
        long expected = unchecked(x * 7L + BitConverter.DoubleToInt64Bits(z) + rec.Key + (rec.Flag ? 1 : 0) + rec.Name.Length);
        Check.Equal(expected, refs(&nx, &ny, &z, native), "ref callback result");
        Check.Equal(unchecked(x + 1), nx, "ref int written back"); Check.Equal(expected, ny, "out long written back");
        NonBlit after = Marshal.PtrToStructure<NonBlit>((IntPtr)native);
        Check.That(after.Key == unchecked(rec.Key * 2) && after.Flag == !rec.Flag && after.Name == "ok" && BitConverter.DoubleToInt64Bits(after.D) == BitConverter.DoubleToInt64Bits(z), $"ref NonBlit written back: {after.Key} {after.Flag} {after.Name} {after.D}");
        // By value: the native caller passes the struct's native layout on the stack (24 bytes: MEMORY class).
        var structVal = (delegate* unmanaged[Cdecl]<NativeNonBlit, int, long>)Marshal.GetFunctionPointerForDelegate(s_structVal);
        Marshal.StructureToPtr(rec, (IntPtr)native, false);
        NativeNonBlit nn = *(NativeNonBlit*)native;
        Check.Equal(unchecked(rec.Key + x * 1000003L + (rec.Flag ? 1 : 0) + rec.Name.Length * 7 + BitConverter.DoubleToInt64Bits(rec.D)), structVal(nn, x), "non-blittable struct by value callback");
        GC.KeepAlive(s_bools); GC.KeepAlive(s_chars); GC.KeepAlive(s_refs); GC.KeepAlive(s_structVal);
    }

    /// <summary>The native layout of NonBlit (int, byte, 6 chars, padding, double): 24 bytes.</summary>
    [StructLayout(LayoutKind.Explicit, Size = 24)] public struct NativeNonBlit { [FieldOffset(0)] public int Key; [FieldOffset(4)] public byte Flag; [FieldOffset(16)] public double D; }
}
