#!/usr/bin/env python3
"""Generates AbiTarget.cs: managed -> unmanaged function pointer -> [UnmanagedCallersOnly] round trips
for many struct shapes (SysV x64 classification: INTEGER / SSE / mixed / MEMORY, padding, Half, Int128,
decimal, Guid), scalar signatures that spill to the stack, small-integer sign extension, and the
delegate-based reverse P/Invoke thunks with marshalled (non-blittable) parameters."""

STRUCTS = [
    # name, fields (type, name)
    ("S4", [("int", "A")]),
    ("S8", [("int", "A"), ("float", "B")]),
    ("S8D", [("double", "D")]),
    ("S12", [("int", "A"), ("int", "B"), ("int", "C")]),
    ("S16", [("long", "A"), ("double", "B")]),
    ("S16D", [("double", "A"), ("double", "B")]),
    ("S16F", [("float", "A"), ("float", "B"), ("float", "C"), ("float", "D")]),
    ("S20", [("int", "A"), ("int", "B"), ("int", "C"), ("int", "D"), ("int", "E")]),
    ("S24", [("long", "A"), ("double", "B"), ("long", "C")]),
    ("S32", [("double", "A"), ("double", "B"), ("double", "C"), ("double", "D")]),
    ("S3", [("byte", "A"), ("byte", "B"), ("byte", "C")]),
    ("S6", [("short", "A"), ("short", "B"), ("short", "C")]),
    ("S7", [("byte", "A"), ("byte", "B"), ("byte", "C"), ("byte", "D"), ("byte", "E"), ("byte", "F"), ("byte", "G")]),
    ("S9", [("byte", "A"), ("long", "B")]),
    ("SFI", [("float", "A"), ("int", "B")]),
    ("SDI", [("double", "A"), ("int", "B")]),
    ("SNested", [("S8", "Inner"), ("long", "L")]),
    ("SHalf", [("Half", "H")]),
    ("SGuid", [("Guid", "G")]),
    ("SPtrB", [("nint", "P"), ("byte", "B")]),
    ("SFloat3", [("float", "A"), ("float", "B"), ("float", "C")]),
    ("SDoubleFloat", [("double", "A"), ("float", "B")]),
    ("SByteFloat", [("byte", "A"), ("float", "B")]),
    ("SLongByte", [("long", "A"), ("byte", "B")]),
    ("SFloatLong", [("float", "A"), ("long", "B")]),
    ("SHalf3", [("Half", "A"), ("Half", "B"), ("Half", "C")]),
    ("S40", [("long", "A"), ("long", "B"), ("long", "C"), ("long", "D"), ("long", "E")]),
    ("SNested24", [("S12", "X"), ("S12", "Y")]),
]

SCALAR_FOLD = {
    "int": "(long){0}", "float": "BitConverter.SingleToInt32Bits({0})", "double": "BitConverter.DoubleToInt64Bits({0})",
    "long": "{0}", "Int128": "(long){0} ^ (long)({0} >> 64)", "byte": "(long){0}", "short": "(long){0}",
    "Half": "BitConverter.HalfToInt16Bits({0})", "decimal": "Fold({0})", "Guid": "Fold({0})", "nint": "(long){0}",
}

def fold_expr(fields, prefix):
    parts = []
    for i, (t, n) in enumerate(fields):
        if t in SCALAR_FOLD:
            e = SCALAR_FOLD[t].format(f"{prefix}.{n}")
        else:
            e = f"Fold({prefix}.{n})"
        parts.append(f"({e}) * {2 * i + 3}")
    return " + ".join(parts) if parts else "0"

out = []
w = out.append
w("// <auto-generated> by gen_abi.py; edit the generator, not this file. </auto-generated>")
w("#nullable disable warnings")
w("using System.Runtime.CompilerServices;")
w("using System.Runtime.InteropServices;")
w("using System.Text;")
w("")
w("namespace SharpFuzzHarness;")
w("")
w("/// <summary>")
w("/// The managed / unmanaged call boundary without any native library: unmanaged function pointers to")
w("/// [UnmanagedCallersOnly] methods (managed-to-unmanaged call, unmanaged-to-managed entry) with structs")
w("/// of every SysV classification passed and returned by value, scalar signatures that spill to the")
w("/// stack, small integers (sign extension), Half / Int128 / decimal / Guid; delegates from function")
w("/// pointers; and delegate thunks (Marshal.GetFunctionPointerForDelegate) whose reverse stubs marshal")
w("/// strings, arrays (from guarded native memory), bools, chars, by-ref and non-blittable structs.")
w("/// </summary>")
w("/// <remarks>Input layout: byte 0 = case, rest = values (structs are filled from the raw bytes).</remarks>")
w("public static unsafe partial class AbiTarget")
w("{")
for name, fields in STRUCTS:
    w(f"    [StructLayout(LayoutKind.Sequential)] public struct {name} {{ " + " ".join(f"public {t} {n};" for t, n in fields) + " }")
w("")
w("    public static long Fold(decimal d) { int[] b = decimal.GetBits(d); return b[0] + 3L * b[1] + 5L * b[2] + 7L * b[3]; }")
w("    public static long Fold(Guid g) { Span<byte> b = stackalloc byte[16]; g.TryWriteBytes(b); return Fold(b); }")
w("    public static long Fold(ReadOnlySpan<byte> b) { long h = 0; foreach (byte x in b) h = h * 31 + x; return h; }")
for name, fields in STRUCTS:
    w(f"    public static long Fold({name} s) => unchecked({fold_expr(fields, 's')});")
w("")
w("    private static T Read<T>(ref FuzzInput input) where T : unmanaged")
w("    {")
w("        T value = default;")
w("        Span<byte> bytes = MemoryMarshal.AsBytes(new Span<T>(ref value));")
w("        input.Bytes(bytes.Length).CopyTo(bytes);")
w("        return value;")
w("    }")
w("")
# Callees
for name, fields in STRUCTS:
    w(f"    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static {name} Echo{name}({name} s) => s;")
    w(f"    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long Mix{name}(int a, {name} s, double d, {name} t, long l, {name} u, float f, {name} v) => unchecked(a + Fold(s) + (long)d + Fold(t) * 3 + l + Fold(u) * 5 + (long)f + Fold(v) * 7);")
    w(f"    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long Many{name}({name} s0, {name} s1, {name} s2, {name} s3, {name} s4, {name} s5, {name} s6, {name} s7, {name} s8, {name} s9, long tail) => unchecked(Fold(s0) + Fold(s1) * 3 + Fold(s2) * 5 + Fold(s3) * 7 + Fold(s4) * 11 + Fold(s5) * 13 + Fold(s6) * 17 + Fold(s7) * 19 + Fold(s8) * 23 + Fold(s9) * 29 + tail);")
    w(f"    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static {name} Pick{name}(long which, {name} a, {name} b, {name} c) => which % 3 == 0 ? a : which % 3 == 1 ? b : c;")
w("")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long Scalars(sbyte a, byte b, short c, ushort d, int e, uint f, long g, ulong h, float i, double j, nint k, sbyte l, short m, float n, double o, byte p, double q, float r, long s, int t) =>")
w("        unchecked(a + 3L * b + 5L * c + 7L * d + 11L * e + 13L * f + 17L * g + 19L * (long)h + 23L * BitConverter.SingleToInt32Bits(i) + 29L * BitConverter.DoubleToInt64Bits(j) + 31L * k + 37L * l + 41L * m + 43L * BitConverter.SingleToInt32Bits(n) + 47L * BitConverter.DoubleToInt64Bits(o) + 53L * p + 59L * BitConverter.DoubleToInt64Bits(q) + 61L * BitConverter.SingleToInt32Bits(r) + 67L * s + 71L * t);")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static sbyte RetSByte(int x) => (sbyte)x;")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static byte RetByte(int x) => (byte)x;")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static short RetShort(int x) => (short)x;")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static ushort RetUShort(int x) => (ushort)x;")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static float RetFloat(double x) => (float)x;")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static Half RetHalf(float x) => (Half)x;")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static int* EchoPtr(int* p) => p;")
w("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])] public static long Halves(Half a, Half b, Half c, Half d, Half e, Half f, Half g, Half h, Half i, Half j) =>")
w("        unchecked(BitConverter.HalfToInt16Bits(a) + 3L * BitConverter.HalfToInt16Bits(b) + 5L * BitConverter.HalfToInt16Bits(c) + 7L * BitConverter.HalfToInt16Bits(d) + 11L * BitConverter.HalfToInt16Bits(e) + 13L * BitConverter.HalfToInt16Bits(f) + 17L * BitConverter.HalfToInt16Bits(g) + 19L * BitConverter.HalfToInt16Bits(h) + 23L * BitConverter.HalfToInt16Bits(i) + 29L * BitConverter.HalfToInt16Bits(j));")
w("")
# Delegate-based reverse P/Invoke with marshalling
w("    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]")
w("    public struct NonBlit { public int Key; [MarshalAs(UnmanagedType.U1)] public bool Flag; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 6)] public string Name; public double D; }")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int StrLenCb([MarshalAs(UnmanagedType.LPUTF8Str)] string s);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int WStrLenCb([MarshalAs(UnmanagedType.LPWStr)] string s);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int AnsiStrLenCb([MarshalAs(UnmanagedType.LPStr)] string s);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long SumArrCb([In, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] int[] a, int n);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int FillArrCb([Out, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] int[] a, int n, int v);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long SumBytesCb([In, MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 1)] byte[] a, int n);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int BoolsCb([MarshalAs(UnmanagedType.U1)] bool a, [MarshalAs(UnmanagedType.Bool)] bool b, [MarshalAs(UnmanagedType.Bool)] bool c, [MarshalAs(UnmanagedType.I1)] bool d);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Unicode)] public delegate int CharsCb(char a, [MarshalAs(UnmanagedType.U1)] char b, [MarshalAs(UnmanagedType.U2)] char c);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long RefsCb(ref int x, out long y, in double z, ref NonBlit s);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long StructValCb(NonBlit s, int k);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] [return: MarshalAs(UnmanagedType.LPUTF8Str)] public delegate string RetStrCb(int n);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate S16 EchoS16Del(S16 s);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate S24 EchoS24Del(S24 s);")
w("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long ScalarsDel(sbyte a, byte b, short c, ushort d, int e, uint f, long g, ulong h, float i, double j, nint k, sbyte l, short m, float n, double o, byte p, double q, float r, long s, int t);")
w("")
w("    private static string s_lastString;")
w("    private static int[] s_lastArray;")
w("    private static readonly StrLenCb s_strLen = s => { s_lastString = s; return s?.Length ?? -1; };")
w("    private static readonly WStrLenCb s_wstrLen = s => { s_lastString = s; return s?.Length ?? -1; };")
w("    private static readonly AnsiStrLenCb s_ansiStrLen = s => { s_lastString = s; return s?.Length ?? -1; };")
w("    private static readonly SumArrCb s_sumArr = (a, n) => { s_lastArray = a; long h = 0; foreach (int x in a ?? []) h = unchecked(h * 31 + x); return unchecked(h + (a?.Length ?? -1) * 1000003L); };")
w("    private static readonly FillArrCb s_fillArr = (a, n, v) => { for (int i = 0; i < (a?.Length ?? 0); i++) a[i] = unchecked(v + i); return a?.Length ?? -1; };")
w("    private static readonly SumBytesCb s_sumBytes = (a, n) => unchecked(Fold(a) + (a?.Length ?? -1) * 1000003L);")
w("    private static readonly BoolsCb s_bools = (a, b, c, d) => (a ? 1 : 0) | (b ? 2 : 0) | (c ? 4 : 0) | (d ? 8 : 0);")
w("    private static readonly CharsCb s_chars = (a, b, c) => a + 3 * b + 5 * c;")
w("    private static readonly RefsCb s_refs = (ref int x, out long y, in double z, ref NonBlit s) => { long r = unchecked(x * 7L + BitConverter.DoubleToInt64Bits(z) + s.Key + (s.Flag ? 1 : 0) + (s.Name?.Length ?? -1)); x = unchecked(x + 1); y = r; s.Key = unchecked(s.Key * 2); s.Flag = !s.Flag; s.Name = \"ok\"; s.D = z; return r; };")
w("    private static readonly StructValCb s_structVal = (s, k) => unchecked(s.Key + k * 1000003L + (s.Flag ? 1 : 0) + (s.Name?.Length ?? -1) * 7 + BitConverter.DoubleToInt64Bits(s.D));")
w("    private static readonly RetStrCb s_retStr = n => n < 0 ? null : new string('x', n % 100) + n;")
w("")
w("    public static void Run(ReadOnlySpan<byte> data)")
w("    {")
w("        var input = new FuzzInput(data);")
w("        int which = input.Byte();")
w(f"        switch (which % {len(STRUCTS) + 4})")
w("        {")
for i, (name, fields) in enumerate(STRUCTS):
    w(f"            case {i}: Struct{name}(ref input); break;")
w(f"            case {len(STRUCTS)}: ScalarCases(ref input); break;")
w(f"            case {len(STRUCTS) + 1}: DelegateCases(ref input); break;")
w(f"            case {len(STRUCTS) + 2}: ReverseStrings(ref input); break;")
w("            default: ReverseValues(ref input); break;")
w("        }")
w("    }")
w("")
for name, fields in STRUCTS:
    w(f"    private static void Struct{name}(ref FuzzInput input)")
    w("    {")
    w(f"        {name} a = Read<{name}>(ref input), b = Read<{name}>(ref input), c = Read<{name}>(ref input), d = Read<{name}>(ref input);")
    w("        int i = input.Int32(); long l = (long)input.Int32() << 32 | (uint)input.Int32(); double dd = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float ff = BitConverter.Int32BitsToSingle(input.Int32());")
    w(f"        delegate* unmanaged[Cdecl]<{name}, {name}> echo = &Echo{name};")
    w(f"        Check.Equal(Fold(a), Fold(echo(a)), \"{name} echo\");")
    w(f"        delegate* unmanaged[Cdecl]<int, {name}, double, {name}, long, {name}, float, {name}, long> mix = &Mix{name};")
    w(f"        Check.Equal(unchecked(i + Fold(a) + (long)dd + Fold(b) * 3 + l + Fold(c) * 5 + (long)ff + Fold(d) * 7), mix(i, a, dd, b, l, c, ff, d), \"{name} mix\");")
    w(f"        delegate* unmanaged[Cdecl]<{name}, {name}, {name}, {name}, {name}, {name}, {name}, {name}, {name}, {name}, long, long> many = &Many{name};")
    w(f"        Check.Equal(unchecked(Fold(a) + Fold(b) * 3 + Fold(c) * 5 + Fold(d) * 7 + Fold(a) * 11 + Fold(b) * 13 + Fold(c) * 17 + Fold(d) * 19 + Fold(a) * 23 + Fold(b) * 29 + l), many(a, b, c, d, a, b, c, d, a, b, l), \"{name} many\");")
    w(f"        delegate* unmanaged[Cdecl]<long, {name}, {name}, {name}, {name}> pick = &Pick{name};")
    w(f"        Check.Equal(Fold(l % 3 == 0 ? a : l % 3 == 1 ? b : c), Fold(pick(l, a, b, c)), \"{name} pick\");")
    w("    }")
    w("")
w("    private static void ScalarCases(ref FuzzInput input)")
w("    {")
w("        sbyte a = (sbyte)input.Byte(); byte b = input.Byte(); short c = (short)input.UInt16(); ushort d = input.UInt16(); int e = input.Int32(); uint f = (uint)input.Int32();")
w("        long g = (long)input.Int32() << 32 | (uint)input.Int32(); ulong h = (ulong)input.Int32() << 32 | (uint)input.Int32(); float i = BitConverter.Int32BitsToSingle(input.Int32()); double j = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32());")
w("        nint k = (nint)input.Int32(); sbyte l = (sbyte)input.Byte(); short m = (short)input.UInt16(); float n = BitConverter.Int32BitsToSingle(input.Int32()); double o = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32());")
w("        byte p = input.Byte(); double q = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32()); float r = BitConverter.Int32BitsToSingle(input.Int32()); long s = (long)input.Int32() << 32 | (uint)input.Int32(); int t = input.Int32();")
w("        long expected = unchecked(a + 3L * b + 5L * c + 7L * d + 11L * e + 13L * f + 17L * g + 19L * (long)h + 23L * BitConverter.SingleToInt32Bits(i) + 29L * BitConverter.DoubleToInt64Bits(j) + 31L * k + 37L * l + 41L * m + 43L * BitConverter.SingleToInt32Bits(n) + 47L * BitConverter.DoubleToInt64Bits(o) + 53L * p + 59L * BitConverter.DoubleToInt64Bits(q) + 61L * BitConverter.SingleToInt32Bits(r) + 67L * s + 71L * t);")
w("        delegate* unmanaged[Cdecl]<sbyte, byte, short, ushort, int, uint, long, ulong, float, double, nint, sbyte, short, float, double, byte, double, float, long, int, long> scalars = &Scalars;")
w("        Check.Equal(expected, scalars(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t), \"scalars\");")
w("        var scalarsDel = Marshal.GetDelegateForFunctionPointer<ScalarsDel>((IntPtr)scalars);")
w("        Check.Equal(expected, scalarsDel(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t), \"scalars through a delegate\");")
w("        delegate* unmanaged[Cdecl]<int, sbyte> retSByte = &RetSByte; Check.Equal((sbyte)e, retSByte(e), \"sbyte return\");")
w("        delegate* unmanaged[Cdecl]<int, byte> retByte = &RetByte; Check.Equal((byte)e, retByte(e), \"byte return\");")
w("        delegate* unmanaged[Cdecl]<int, short> retShort = &RetShort; Check.Equal((short)e, retShort(e), \"short return\");")
w("        delegate* unmanaged[Cdecl]<int, ushort> retUShort = &RetUShort; Check.Equal((ushort)e, retUShort(e), \"ushort return\");")
w("        delegate* unmanaged[Cdecl]<double, float> retFloat = &RetFloat; Check.Equal(BitConverter.SingleToInt32Bits((float)j), BitConverter.SingleToInt32Bits(retFloat(j)), \"float return\");")
w("        delegate* unmanaged[Cdecl]<float, Half> retHalf = &RetHalf; Check.Equal(BitConverter.HalfToInt16Bits((Half)i), BitConverter.HalfToInt16Bits(retHalf(i)), \"Half return\");")
w("        int local = e; delegate* unmanaged[Cdecl]<int*, int*> echoPtr = &EchoPtr; Check.That(echoPtr(&local) == &local, \"pointer echo\");")
w("        delegate* unmanaged[Cdecl]<Half, Half, Half, Half, Half, Half, Half, Half, Half, Half, long> halves = &Halves;")
w("        Half h0 = (Half)i, h1 = (Half)j, h2 = (Half)n, h3 = (Half)o, h4 = (Half)q, h5 = (Half)r, h6 = BitConverter.Int16BitsToHalf(c), h7 = BitConverter.Int16BitsToHalf((short)d), h8 = BitConverter.Int16BitsToHalf(m), h9 = BitConverter.Int16BitsToHalf((short)e);")
w("        Check.Equal(unchecked(BitConverter.HalfToInt16Bits(h0) + 3L * BitConverter.HalfToInt16Bits(h1) + 5L * BitConverter.HalfToInt16Bits(h2) + 7L * BitConverter.HalfToInt16Bits(h3) + 11L * BitConverter.HalfToInt16Bits(h4) + 13L * BitConverter.HalfToInt16Bits(h5) + 17L * BitConverter.HalfToInt16Bits(h6) + 19L * BitConverter.HalfToInt16Bits(h7) + 23L * BitConverter.HalfToInt16Bits(h8) + 29L * BitConverter.HalfToInt16Bits(h9)), halves(h0, h1, h2, h3, h4, h5, h6, h7, h8, h9), \"ten Halves\");")
w("    }")
w("")
w("    private static void DelegateCases(ref FuzzInput input)")
w("    {")
w("        S16 a = Read<S16>(ref input); S24 b = Read<S24>(ref input);")
w("        delegate* unmanaged[Cdecl]<S16, S16> e16 = &EchoS16; delegate* unmanaged[Cdecl]<S24, S24> e24 = &EchoS24;")
w("        var d16 = Marshal.GetDelegateForFunctionPointer<EchoS16Del>((IntPtr)e16); var d24 = Marshal.GetDelegateForFunctionPointer<EchoS24Del>((IntPtr)e24);")
w("        Check.Equal(Fold(a), Fold(d16(a)), \"S16 echo through a delegate\"); Check.Equal(Fold(b), Fold(d24(b)), \"S24 echo through a delegate\");")
w("        // A managed delegate exposed as a function pointer and called through it: the reverse thunk for blittable structs.")
w("        EchoS16Del m16 = s => new S16 { A = s.A + 1, B = s.B * 2 }; EchoS24Del m24 = s => new S24 { A = s.C, B = s.B, C = s.A };")
w("        var f16 = (delegate* unmanaged[Cdecl]<S16, S16>)Marshal.GetFunctionPointerForDelegate(m16); var f24 = (delegate* unmanaged[Cdecl]<S24, S24>)Marshal.GetFunctionPointerForDelegate(m24);")
w("        S16 r16 = f16(a); S24 r24 = f24(b);")
w("        Check.That(r16.A == a.A + 1 && BitConverter.DoubleToInt64Bits(r16.B) == BitConverter.DoubleToInt64Bits(a.B * 2), \"S16 through a delegate thunk\");")
w("        Check.That(r24.A == b.C && BitConverter.DoubleToInt64Bits(r24.B) == BitConverter.DoubleToInt64Bits(b.B) && r24.C == b.A, \"S24 through a delegate thunk\");")
w("        GC.KeepAlive(m16); GC.KeepAlive(m24);")
w("    }")
w("")
w("    /// <summary>Delegate thunks whose reverse stubs marshal strings and arrays from guarded native memory.</summary>")
w("    private static void ReverseStrings(ref FuzzInput input)")
w("    {")
w("        byte flags = input.Byte();")
w("        byte[] text = input.SegmentBytes().ToArray();")
w("        int[] ints = MemoryMarshal.Cast<byte, int>(input.Bytes(Math.Min(input.Remaining, 64))).ToArray();")
w("        bool atStart = (flags & 1) != 0;")
w("        // UTF-8, NUL last before the guard page.")
w("        byte* utf8 = Guarded.Allocate(text.Length + 1, atStart);")
w("        text.CopyTo(new Span<byte>(utf8, text.Length)); utf8[text.Length] = 0;")
w("        string expected = Encoding.UTF8.GetString(text);")
w("        var strLen = (delegate* unmanaged[Cdecl]<byte*, int>)Marshal.GetFunctionPointerForDelegate(s_strLen);")
w("        Check.Equal(expected.Length, strLen(utf8), \"LPUTF8Str callback length\"); Check.Equal(expected, s_lastString, \"LPUTF8Str callback string\");")
w("        Check.Equal(-1, strLen(null), \"LPUTF8Str callback null\");")
w("        var ansiLen = (delegate* unmanaged[Cdecl]<byte*, int>)Marshal.GetFunctionPointerForDelegate(s_ansiStrLen);")
w("        Check.Equal(expected.Length, ansiLen(utf8), \"LPStr callback length\"); Check.Equal(expected, s_lastString, \"LPStr callback string\");")
w("        // UTF-16, NUL char last.")
w("        char[] wide = Encoding.Unicode.GetString(text, 0, text.Length & ~1).ToCharArray();")
w("        int nul = Array.IndexOf(wide, '\\0'); if (nul >= 0) wide = wide.AsSpan(0, nul).ToArray();")
w("        char* utf16 = (char*)Guarded.Allocate((wide.Length + 1) * 2L, !atStart);")
w("        wide.CopyTo(new Span<char>(utf16, wide.Length)); utf16[wide.Length] = '\\0';")
w("        var wstrLen = (delegate* unmanaged[Cdecl]<char*, int>)Marshal.GetFunctionPointerForDelegate(s_wstrLen);")
w("        Check.Equal(wide.Length, wstrLen(utf16), \"LPWStr callback length\"); Check.Equal(new string(wide), s_lastString, \"LPWStr callback string\");")
w("        // [In] int[] with SizeParamIndex from exactly n guarded ints; [Out] int[] written back into exactly n guarded ints.")
w("        int* nativeInts = (int*)Guarded.Allocate(ints.Length * 4L, atStart);")
w("        ints.CopyTo(new Span<int>(nativeInts, ints.Length));")
w("        var sumArr = (delegate* unmanaged[Cdecl]<int*, int, long>)Marshal.GetFunctionPointerForDelegate(s_sumArr);")
w("        long h = 0; foreach (int x in ints) h = unchecked(h * 31 + x);")
w("        Check.Equal(unchecked(h + ints.Length * 1000003L), sumArr(nativeInts, ints.Length), \"[In] int[] callback\");")
w("        Check.That(s_lastArray is not null && s_lastArray.SequenceEqual(ints), \"[In] int[] callback contents\");")
w("        Check.Equal(-1000003L, sumArr(null, 3), \"[In] int[] callback null\");")
w("        var fillArr = (delegate* unmanaged[Cdecl]<int*, int, int, int>)Marshal.GetFunctionPointerForDelegate(s_fillArr);")
w("        int v = flags * 1000;")
w("        Check.Equal(ints.Length, fillArr(nativeInts, ints.Length, v), \"[Out] int[] callback\");")
w("        for (int i = 0; i < ints.Length; i++) Check.Equal(unchecked(v + i), nativeInts[i], $\"[Out] int[] callback element {i}\");")
w("        var sumBytes = (delegate* unmanaged[Cdecl]<byte*, int, long>)Marshal.GetFunctionPointerForDelegate(s_sumBytes);")
w("        Check.Equal(unchecked(Fold(text) + text.Length * 1000003L), sumBytes(utf8, text.Length), \"[In] byte[] callback\");")
w("        // A string returned from a callback is a CoTaskMem UTF-8 copy the caller owns.")
w("        var retStr = (delegate* unmanaged[Cdecl]<int, byte*>)Marshal.GetFunctionPointerForDelegate(s_retStr);")
w("        int n = ints.Length > 0 ? ints[0] : flags;")
w("        byte* ret = retStr(n);")
w("        if (n < 0) Check.That(ret == null, \"null string return\");")
w("        else { Check.Equal(new string('x', n % 100) + n, Marshal.PtrToStringUTF8((IntPtr)ret), \"string return\"); Marshal.FreeCoTaskMem((IntPtr)ret); }")
w("        GC.KeepAlive(s_strLen); GC.KeepAlive(s_wstrLen); GC.KeepAlive(s_ansiStrLen); GC.KeepAlive(s_sumArr); GC.KeepAlive(s_fillArr); GC.KeepAlive(s_sumBytes); GC.KeepAlive(s_retStr);")
w("    }")
w("")
w("    /// <summary>Delegate thunks marshalling bools, chars, by-ref values and non-blittable structs.</summary>")
w("    private static void ReverseValues(ref FuzzInput input)")
w("    {")
w("        byte ba = input.Byte(); int bb = input.Int32(); int bc = input.Int32(); byte bd = input.Byte();")
w("        var bools = (delegate* unmanaged[Cdecl]<byte, int, int, sbyte, int>)Marshal.GetFunctionPointerForDelegate(s_bools);")
w("        Check.Equal((ba != 0 ? 1 : 0) | (bb != 0 ? 2 : 0) | (bc != 0 ? 4 : 0) | (bd != 0 ? 8 : 0), bools(ba, bb, bc, (sbyte)bd), \"bool callback\");")
w("        // char in an unmanaged function pointer signature would be marshalled as ANSI by the caller, so the raw UTF-16 units go through ushort.")
w("        ushort ca = input.UInt16(); byte cb = (byte)(input.Byte() & 0x7F); ushort cc = input.UInt16();")
w("        var chars = (delegate* unmanaged[Cdecl]<ushort, byte, ushort, int>)Marshal.GetFunctionPointerForDelegate(s_chars);")
w("        Check.Equal(ca + 3 * cb + 5 * cc, chars(ca, cb, cc), \"char callback\");")
w("        int x = input.Int32(); double z = BitConverter.Int64BitsToDouble((long)input.Int32() << 32 | (uint)input.Int32());")
w("        var rec = new NonBlit { Key = input.Int32(), Flag = (input.Byte() & 1) != 0, Name = new string((char)('a' + input.Byte() % 26), input.Byte() % 6), D = z };")
w("        int size = Marshal.SizeOf<NonBlit>();")
w("        byte* native = Guarded.Allocate(size, (x & 1) != 0);")
w("        Marshal.StructureToPtr(rec, (IntPtr)native, false);")
w("        int nx = x; long ny = 0;")
w("        var refs = (delegate* unmanaged[Cdecl]<int*, long*, double*, byte*, long>)Marshal.GetFunctionPointerForDelegate(s_refs);")
w("        long expected = unchecked(x * 7L + BitConverter.DoubleToInt64Bits(z) + rec.Key + (rec.Flag ? 1 : 0) + rec.Name.Length);")
w("        Check.Equal(expected, refs(&nx, &ny, &z, native), \"ref callback result\");")
w("        Check.Equal(unchecked(x + 1), nx, \"ref int written back\"); Check.Equal(expected, ny, \"out long written back\");")
w("        NonBlit after = Marshal.PtrToStructure<NonBlit>((IntPtr)native);")
w("        Check.That(after.Key == unchecked(rec.Key * 2) && after.Flag == !rec.Flag && after.Name == \"ok\" && BitConverter.DoubleToInt64Bits(after.D) == BitConverter.DoubleToInt64Bits(z), $\"ref NonBlit written back: {after.Key} {after.Flag} {after.Name} {after.D}\");")
w("        // By value: the native caller passes the struct's native layout on the stack (24 bytes: MEMORY class).")
w("        var structVal = (delegate* unmanaged[Cdecl]<NativeNonBlit, int, long>)Marshal.GetFunctionPointerForDelegate(s_structVal);")
w("        Marshal.StructureToPtr(rec, (IntPtr)native, false);")
w("        NativeNonBlit nn = *(NativeNonBlit*)native;")
w("        Check.Equal(unchecked(rec.Key + x * 1000003L + (rec.Flag ? 1 : 0) + rec.Name.Length * 7 + BitConverter.DoubleToInt64Bits(rec.D)), structVal(nn, x), \"non-blittable struct by value callback\");")
w("        GC.KeepAlive(s_bools); GC.KeepAlive(s_chars); GC.KeepAlive(s_refs); GC.KeepAlive(s_structVal);")
w("    }")
w("")
w("    /// <summary>The native layout of NonBlit (int, byte, 6 chars, padding, double): 24 bytes.</summary>")
w("    [StructLayout(LayoutKind.Explicit, Size = 24)] public struct NativeNonBlit { [FieldOffset(0)] public int Key; [FieldOffset(4)] public byte Flag; [FieldOffset(16)] public double D; }")
w("}")

import os
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "AbiTarget.cs")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print(f"wrote {path}: {len(out)} lines")
