#nullable disable warnings
// <auto-generated> by gen_vector.py: the same operations through Vector128 / 256 / 512 and Vector<T>.
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;

namespace SharpFuzzHarness;

/// <summary>
/// The System.Runtime.Intrinsics vector APIs (Vector128 / 256 / 512 and Vector&lt;T&gt;) for every
/// primitive element type, against a scalar model built on generic math. Vector widths the hardware
/// doesn't accelerate (Vector512 without AVX-512, which the secondary instances disable) run the
/// software fallbacks built on Unsafe; accelerated ones go through the JIT's intrinsics. Operands are
/// loaded with LoadUnsafe from, and results stored with StoreUnsafe to, guarded memory
/// (see <see cref="Guarded"/>) that ends right after the last vector.
/// </summary>
/// <remarks>
/// Input layout:
///   byte 0     element type; byte 1 operation; byte 2 shift count
///   rest       256 bytes: operands a, b, c and a mask, 64 bytes each (zero-filled)
/// </remarks>
public static class VectorOpsTarget
{
    private static readonly (string Name, string Kinds, bool Exact)[] s_ops =
    [
        ("Add", "all", false),
        ("Subtract", "all", false),
        ("Multiply", "all", false),
        ("MultiplyScalar", "all", false),
        ("Min", "all", false),
        ("Max", "all", false),
        ("MinNumber", "all", false),
        ("MaxNumber", "all", false),
        ("MaxMagnitude", "all", false),
        ("Clamp", "all", false),
        ("Abs", "all", false),
        ("Negate", "all", false),
        ("Equals", "all", true),
        ("LessThan", "all", true),
        ("GreaterThanOrEqual", "all", true),
        ("ConditionalSelect", "all", true),
        ("And", "all", true),
        ("Or", "all", true),
        ("Xor", "all", true),
        ("AndNot", "all", true),
        ("OnesComplement", "all", true),
        ("ShiftLeft", "int", true),
        ("ShiftRight", "int", true),
        ("ShiftRightLogical", "int", true),
        ("CopySign", "signed", false),
        ("Sqrt", "fp", false),
        ("Floor", "fp", false),
        ("Ceiling", "fp", false),
        ("Round", "fp", false),
        ("Truncate", "fp", false),
        ("FusedMultiplyAdd", "fp", false),
        ("IsNaN", "all", true),
        ("IsNegative", "all", true),
        ("IsZero", "all", true),
    ];

    public static void Run(ReadOnlySpan<byte> data)
    {
        var input = new FuzzInput(data);
        byte type = input.Byte();
        byte op = input.Byte();
        byte shift = input.Byte();
        Span<byte> raw = stackalloc byte[256];
        raw.Clear();
        ReadOnlySpan<byte> rest = input.Rest();
        rest[..Math.Min(rest.Length, 256)].CopyTo(raw);
        switch (type % 10)
        {
            case 0: Test<sbyte>(op, shift, raw, "int", true); break;
            case 1: Test<byte>(op, shift, raw, "int", false); break;
            case 2: Test<short>(op, shift, raw, "int", true); break;
            case 3: Test<ushort>(op, shift, raw, "int", false); break;
            case 4: Test<int>(op, shift, raw, "int", true); break;
            case 5: Test<uint>(op, shift, raw, "int", false); break;
            case 6: Test<long>(op, shift, raw, "int", true); break;
            case 7: Test<ulong>(op, shift, raw, "int", false); break;
            case 8: Test<float>(op, shift, raw, "fp", true); break;
            default: Test<double>(op, shift, raw, "fp", true); break;
        }
    }

    private static bool IsFloat<T>() => typeof(T) == typeof(float) || typeof(T) == typeof(double);

    private static void Test<T>(byte op, byte shift, ReadOnlySpan<byte> raw, string kind, bool signed)
        where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T>
    {
        int index = op % s_ops.Length;
        (string name, string kinds, bool exact) = s_ops[index];
        if (kinds == "int" && kind != "int" || kinds == "fp" && kind != "fp" || kinds == "signed" && !signed)
        {
            return;
        }

        int elements = 64 / Unsafe.SizeOf<T>();
        T[] a = MemoryMarshal.Cast<byte, T>(raw[..64]).ToArray();
        T[] b = MemoryMarshal.Cast<byte, T>(raw[64..128]).ToArray();
        T[] c = MemoryMarshal.Cast<byte, T>(raw[128..192]).ToArray();
        T[] mask = MemoryMarshal.Cast<byte, T>(raw[192..256]).ToArray();
        T s = b[^1];
        int n = shift;
        T[] expected = new T[elements];
        for (int i = 0; i < elements; i++)
        {
            T x = a[i], y = b[i], z = c[i], m = mask[i];
            expected[i] = index switch
            {
                0 => ModelAdd(x, y, z, m, s, n),
                1 => ModelSubtract(x, y, z, m, s, n),
                2 => ModelMultiply(x, y, z, m, s, n),
                3 => ModelMultiplyScalar(x, y, z, m, s, n),
                4 => ModelMin(x, y, z, m, s, n),
                5 => ModelMax(x, y, z, m, s, n),
                6 => ModelMinNumber(x, y, z, m, s, n),
                7 => ModelMaxNumber(x, y, z, m, s, n),
                8 => ModelMaxMagnitude(x, y, z, m, s, n),
                9 => ModelClamp(x, y, z, m, s, n),
                10 => ModelAbs(x, y, z, m, s, n),
                11 => ModelNegate(x, y, z, m, s, n),
                12 => ModelEquals(x, y, z, m, s, n),
                13 => ModelLessThan(x, y, z, m, s, n),
                14 => ModelGreaterThanOrEqual(x, y, z, m, s, n),
                15 => ModelConditionalSelect(x, y, z, m, s, n),
                16 => ModelAnd(x, y, z, m, s, n),
                17 => ModelOr(x, y, z, m, s, n),
                18 => ModelXor(x, y, z, m, s, n),
                19 => ModelAndNot(x, y, z, m, s, n),
                20 => ModelOnesComplement(x, y, z, m, s, n),
                21 => ModelShiftLeft(x, y, z, m, s, n),
                22 => ModelShiftRight(x, y, z, m, s, n),
                23 => ModelShiftRightLogical(x, y, z, m, s, n),
                24 => ModelCopySign(x, y, z, m, s, n),
                25 => ModelSqrt(x, y, z, m, s, n),
                26 => ModelFloor(x, y, z, m, s, n),
                27 => ModelCeiling(x, y, z, m, s, n),
                28 => ModelRound(x, y, z, m, s, n),
                29 => ModelTruncate(x, y, z, m, s, n),
                30 => ModelFusedMultiplyAdd(x, y, z, m, s, n),
                31 => ModelIsNaN(x, y, z, m, s, n),
                32 => ModelIsNegative(x, y, z, m, s, n),
                33 => ModelIsZero(x, y, z, m, s, n),
                _ => x,
            };
        }

        string what = $"{name}<{typeof(T).Name}> shift {n}";
        foreach (string width in (string[])["128", "256", "512", "Vec"])
        {
            // Operands and result in guarded memory that ends right after the last element.
            Span<T> ga = Guarded.Copy<T>(a, atStart: false), gb = Guarded.Copy<T>(b, false), gc = Guarded.Copy<T>(c, false), gm = Guarded.Copy<T>(mask, false);
            Span<T> result = Guarded.Copy<T>(new T[elements], false);
            switch (width)
            {
                case "128": Run128(index, ga, gb, gc, gm, s, n, result); break;
                case "256": Run256(index, ga, gb, gc, gm, s, n, result); break;
                case "512": Run512(index, ga, gb, gc, gm, s, n, result); break;
                default: RunVec(index, ga, gb, gc, gm, s, n, result); break;
            }

            int covered = width == "Vec" ? elements / Vector<T>.Count * Vector<T>.Count : elements;
            for (int i = 0; i < covered; i++)
            {
                if (!(exact ? Bits(expected[i]) == Bits(result[i]) : Same(expected[i], result[i])))
                {
                    Check.That(false, $"Vector{width} {what}: element {i} is {result[i]} (0x{Bits(result[i])}), expected {expected[i]} (0x{Bits(expected[i])}); a {a[i]} (0x{Bits(a[i])}) b {b[i]} (0x{Bits(b[i])}) c {c[i]} m 0x{Bits(mask[i])}");
                }
            }
        }
    }

    private static string Bits<T>(T value) where T : unmanaged
    {
        Span<byte> bytes = stackalloc byte[Unsafe.SizeOf<T>()];
        MemoryMarshal.Write(bytes, in value);
        bytes.Reverse();
        return Convert.ToHexString(bytes);
    }

    // Bitwise equality, except that any NaN matches any NaN (payloads and signs of NaN results aren't specified).
    private static bool Same<T>(T x, T y) where T : unmanaged, INumber<T> =>
        Bits(x) == Bits(y) || T.IsNaN(x) && T.IsNaN(y);

    private static T AllBits<T>(bool condition) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> =>
        condition ? ~T.Zero : T.Zero;

    private static T ModelAdd<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => unchecked(x + y);
    private static T ModelSubtract<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => unchecked(x - y);
    private static T ModelMultiply<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => unchecked(x * y);
    private static T ModelMultiplyScalar<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => unchecked(x * s);
    private static T ModelMin<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => T.Min(x, y);
    private static T ModelMax<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => T.Max(x, y);
    private static T ModelMinNumber<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => T.MinNumber(x, y);
    private static T ModelMaxNumber<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => T.MaxNumber(x, y);
    private static T ModelMaxMagnitude<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => T.MaxMagnitude(x, y);
    private static T ModelClamp<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => T.Min(T.Max(x, T.Min(y, z)), T.Max(y, z));
    private static T ModelAbs<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => T.IsNegative(x) ? unchecked(T.Zero - x) : x;
    private static T ModelNegate<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => unchecked(-x);
    private static T ModelEquals<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => AllBits<T>(x == y);
    private static T ModelLessThan<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => AllBits<T>(x < y);
    private static T ModelGreaterThanOrEqual<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => AllBits<T>(x >= y);
    private static T ModelConditionalSelect<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => (m & x) | (~m & y);
    private static T ModelAnd<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => x & y;
    private static T ModelOr<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => x | y;
    private static T ModelXor<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => x ^ y;
    private static T ModelAndNot<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => x & ~y;
    private static T ModelOnesComplement<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => ~x;
    private static T ModelShiftLeft<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Shift(x, n, 0);
    private static T ModelShiftRight<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Shift(x, n, 1);
    private static T ModelShiftRightLogical<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Shift(x, n, 2);
    private static T ModelCopySign<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => IsFloat<T>() ? T.CopySign(x, y) : (T.IsNegative(x) == T.IsNegative(y) ? x : unchecked(T.Zero - x));
    private static T ModelSqrt<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Fp(x, y, z, 0);
    private static T ModelFloor<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Fp(x, y, z, 1);
    private static T ModelCeiling<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Fp(x, y, z, 2);
    private static T ModelRound<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Fp(x, y, z, 3);
    private static T ModelTruncate<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Fp(x, y, z, 4);
    private static T ModelFusedMultiplyAdd<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => Fp(x, y, z, 5);
    private static T ModelIsNaN<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => AllBits<T>(T.IsNaN(x));
    private static T ModelIsNegative<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => AllBits<T>(T.IsNegative(x));
    private static T ModelIsZero<T>(T x, T y, T z, T m, T s, int n) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T> => AllBits<T>(T.IsZero(x));

    /// <summary>Shifts with the count masked to the element width (0 left, 1 right: arithmetic for signed types, 2 logical right).</summary>
    private static T Shift<T>(T x, int n, int kind) where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T>
    {
        int bits = Unsafe.SizeOf<T>() * 8;
        n &= bits - 1;
        bool signedType = T.IsNegative(unchecked(T.Zero - T.One));
        ulong u = bits switch { 8 => Unsafe.As<T, byte>(ref x), 16 => Unsafe.As<T, ushort>(ref x), 32 => Unsafe.As<T, uint>(ref x), _ => Unsafe.As<T, ulong>(ref x) };
        ulong mask = bits == 64 ? ulong.MaxValue : (1UL << bits) - 1;
        bool negative = (u >> (bits - 1) & 1) != 0;
        ulong r = kind switch
        {
            0 => (u << n) & mask,
            1 when signedType && negative && n > 0 => (u >> n) | (mask & ~(mask >> n)),
            _ => u >> n,
        };
        T result = default;
        switch (bits)
        {
            case 8: Unsafe.As<T, byte>(ref result) = (byte)r; break;
            case 16: Unsafe.As<T, ushort>(ref result) = (ushort)r; break;
            case 32: Unsafe.As<T, uint>(ref result) = (uint)r; break;
            default: Unsafe.As<T, ulong>(ref result) = r; break;
        }

        return result;
    }

    private static T Fp<T>(T x, T y, T z, int kind) where T : unmanaged, INumber<T>
    {
        if (typeof(T) == typeof(float))
        {
            float a = (float)(object)x, b = (float)(object)y, c = (float)(object)z;
            float r = kind switch { 0 => MathF.Sqrt(a), 1 => MathF.Floor(a), 2 => MathF.Ceiling(a), 3 => MathF.Round(a), 4 => MathF.Truncate(a), _ => MathF.FusedMultiplyAdd(a, b, c) };
            return (T)(object)r;
        }

        double da = (double)(object)x, db = (double)(object)y, dc = (double)(object)z;
        double dr = kind switch { 0 => Math.Sqrt(da), 1 => Math.Floor(da), 2 => Math.Ceiling(da), 3 => Math.Round(da), 4 => Math.Truncate(da), _ => Math.FusedMultiplyAdd(da, db, dc) };
        return (T)(object)dr;
    }

    private static void Run128<T>(int op, Span<T> a, Span<T> b, Span<T> c, Span<T> mask, T s, int n, Span<T> result)
        where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T>
    {
        int count = Vector128<T>.Count;
        for (int i = 0; i + count <= a.Length; i += count)
        {
            Vector128<T> x = Vector128.LoadUnsafe(ref MemoryMarshal.GetReference(a), (nuint)i);
            Vector128<T> y = Vector128.LoadUnsafe(ref MemoryMarshal.GetReference(b), (nuint)i);
            Vector128<T> z = Vector128.LoadUnsafe(ref MemoryMarshal.GetReference(c), (nuint)i);
            Vector128<T> m = Vector128.LoadUnsafe(ref MemoryMarshal.GetReference(mask), (nuint)i);
            Vector128<T> r = op switch
            {
                0 => Vector128.Add(x, y),
                1 => Vector128.Subtract(x, y),
                2 => Vector128.Multiply(x, y),
                3 => Vector128.Multiply(x, s),
                4 => Vector128.Min(x, y),
                5 => Vector128.Max(x, y),
                6 => Vector128.MinNumber(x, y),
                7 => Vector128.MaxNumber(x, y),
                8 => Vector128.MaxMagnitude(x, y),
                9 => Vector128.Clamp(x, Vector128.Min(y, z), Vector128.Max(y, z)),
                10 => Vector128.Abs(x),
                11 => Vector128.Negate(x),
                12 => Vector128.Equals(x, y),
                13 => Vector128.LessThan(x, y),
                14 => Vector128.GreaterThanOrEqual(x, y),
                15 => Vector128.ConditionalSelect(m, x, y),
                16 => Vector128.BitwiseAnd(x, y),
                17 => Vector128.BitwiseOr(x, y),
                18 => Vector128.Xor(x, y),
                19 => Vector128.AndNot(x, y),
                20 => Vector128.OnesComplement(x),
                21 => (x << n),
                22 => (x >> n),
                23 => (x >>> n),
                24 => Vector128.CopySign(x, y),
                25 => (typeof(T) == typeof(float) ? Vector128.Sqrt(x.As<T, float>()).As<float, T>() : Vector128.Sqrt(x.As<T, double>()).As<double, T>()),
                26 => (typeof(T) == typeof(float) ? Vector128.Floor(x.As<T, float>()).As<float, T>() : Vector128.Floor(x.As<T, double>()).As<double, T>()),
                27 => (typeof(T) == typeof(float) ? Vector128.Ceiling(x.As<T, float>()).As<float, T>() : Vector128.Ceiling(x.As<T, double>()).As<double, T>()),
                28 => (typeof(T) == typeof(float) ? Vector128.Round(x.As<T, float>()).As<float, T>() : Vector128.Round(x.As<T, double>()).As<double, T>()),
                29 => (typeof(T) == typeof(float) ? Vector128.Truncate(x.As<T, float>()).As<float, T>() : Vector128.Truncate(x.As<T, double>()).As<double, T>()),
                30 => (typeof(T) == typeof(float) ? Vector128.FusedMultiplyAdd(x.As<T, float>(), y.As<T, float>(), z.As<T, float>()).As<float, T>() : Vector128.FusedMultiplyAdd(x.As<T, double>(), y.As<T, double>(), z.As<T, double>()).As<double, T>()),
                31 => Vector128.IsNaN(x),
                32 => Vector128.IsNegative(x),
                33 => Vector128.IsZero(x),
                _ => x,
            };
            r.StoreUnsafe(ref MemoryMarshal.GetReference(result), (nuint)i);
        }
    }
    private static void Run256<T>(int op, Span<T> a, Span<T> b, Span<T> c, Span<T> mask, T s, int n, Span<T> result)
        where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T>
    {
        int count = Vector256<T>.Count;
        for (int i = 0; i + count <= a.Length; i += count)
        {
            Vector256<T> x = Vector256.LoadUnsafe(ref MemoryMarshal.GetReference(a), (nuint)i);
            Vector256<T> y = Vector256.LoadUnsafe(ref MemoryMarshal.GetReference(b), (nuint)i);
            Vector256<T> z = Vector256.LoadUnsafe(ref MemoryMarshal.GetReference(c), (nuint)i);
            Vector256<T> m = Vector256.LoadUnsafe(ref MemoryMarshal.GetReference(mask), (nuint)i);
            Vector256<T> r = op switch
            {
                0 => Vector256.Add(x, y),
                1 => Vector256.Subtract(x, y),
                2 => Vector256.Multiply(x, y),
                3 => Vector256.Multiply(x, s),
                4 => Vector256.Min(x, y),
                5 => Vector256.Max(x, y),
                6 => Vector256.MinNumber(x, y),
                7 => Vector256.MaxNumber(x, y),
                8 => Vector256.MaxMagnitude(x, y),
                9 => Vector256.Clamp(x, Vector256.Min(y, z), Vector256.Max(y, z)),
                10 => Vector256.Abs(x),
                11 => Vector256.Negate(x),
                12 => Vector256.Equals(x, y),
                13 => Vector256.LessThan(x, y),
                14 => Vector256.GreaterThanOrEqual(x, y),
                15 => Vector256.ConditionalSelect(m, x, y),
                16 => Vector256.BitwiseAnd(x, y),
                17 => Vector256.BitwiseOr(x, y),
                18 => Vector256.Xor(x, y),
                19 => Vector256.AndNot(x, y),
                20 => Vector256.OnesComplement(x),
                21 => (x << n),
                22 => (x >> n),
                23 => (x >>> n),
                24 => Vector256.CopySign(x, y),
                25 => (typeof(T) == typeof(float) ? Vector256.Sqrt(x.As<T, float>()).As<float, T>() : Vector256.Sqrt(x.As<T, double>()).As<double, T>()),
                26 => (typeof(T) == typeof(float) ? Vector256.Floor(x.As<T, float>()).As<float, T>() : Vector256.Floor(x.As<T, double>()).As<double, T>()),
                27 => (typeof(T) == typeof(float) ? Vector256.Ceiling(x.As<T, float>()).As<float, T>() : Vector256.Ceiling(x.As<T, double>()).As<double, T>()),
                28 => (typeof(T) == typeof(float) ? Vector256.Round(x.As<T, float>()).As<float, T>() : Vector256.Round(x.As<T, double>()).As<double, T>()),
                29 => (typeof(T) == typeof(float) ? Vector256.Truncate(x.As<T, float>()).As<float, T>() : Vector256.Truncate(x.As<T, double>()).As<double, T>()),
                30 => (typeof(T) == typeof(float) ? Vector256.FusedMultiplyAdd(x.As<T, float>(), y.As<T, float>(), z.As<T, float>()).As<float, T>() : Vector256.FusedMultiplyAdd(x.As<T, double>(), y.As<T, double>(), z.As<T, double>()).As<double, T>()),
                31 => Vector256.IsNaN(x),
                32 => Vector256.IsNegative(x),
                33 => Vector256.IsZero(x),
                _ => x,
            };
            r.StoreUnsafe(ref MemoryMarshal.GetReference(result), (nuint)i);
        }
    }
    private static void Run512<T>(int op, Span<T> a, Span<T> b, Span<T> c, Span<T> mask, T s, int n, Span<T> result)
        where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T>
    {
        int count = Vector512<T>.Count;
        for (int i = 0; i + count <= a.Length; i += count)
        {
            Vector512<T> x = Vector512.LoadUnsafe(ref MemoryMarshal.GetReference(a), (nuint)i);
            Vector512<T> y = Vector512.LoadUnsafe(ref MemoryMarshal.GetReference(b), (nuint)i);
            Vector512<T> z = Vector512.LoadUnsafe(ref MemoryMarshal.GetReference(c), (nuint)i);
            Vector512<T> m = Vector512.LoadUnsafe(ref MemoryMarshal.GetReference(mask), (nuint)i);
            Vector512<T> r = op switch
            {
                0 => Vector512.Add(x, y),
                1 => Vector512.Subtract(x, y),
                2 => Vector512.Multiply(x, y),
                3 => Vector512.Multiply(x, s),
                4 => Vector512.Min(x, y),
                5 => Vector512.Max(x, y),
                6 => Vector512.MinNumber(x, y),
                7 => Vector512.MaxNumber(x, y),
                8 => Vector512.MaxMagnitude(x, y),
                9 => Vector512.Clamp(x, Vector512.Min(y, z), Vector512.Max(y, z)),
                10 => Vector512.Abs(x),
                11 => Vector512.Negate(x),
                12 => Vector512.Equals(x, y),
                13 => Vector512.LessThan(x, y),
                14 => Vector512.GreaterThanOrEqual(x, y),
                15 => Vector512.ConditionalSelect(m, x, y),
                16 => Vector512.BitwiseAnd(x, y),
                17 => Vector512.BitwiseOr(x, y),
                18 => Vector512.Xor(x, y),
                19 => Vector512.AndNot(x, y),
                20 => Vector512.OnesComplement(x),
                21 => (x << n),
                22 => (x >> n),
                23 => (x >>> n),
                24 => Vector512.CopySign(x, y),
                25 => (typeof(T) == typeof(float) ? Vector512.Sqrt(x.As<T, float>()).As<float, T>() : Vector512.Sqrt(x.As<T, double>()).As<double, T>()),
                26 => (typeof(T) == typeof(float) ? Vector512.Floor(x.As<T, float>()).As<float, T>() : Vector512.Floor(x.As<T, double>()).As<double, T>()),
                27 => (typeof(T) == typeof(float) ? Vector512.Ceiling(x.As<T, float>()).As<float, T>() : Vector512.Ceiling(x.As<T, double>()).As<double, T>()),
                28 => (typeof(T) == typeof(float) ? Vector512.Round(x.As<T, float>()).As<float, T>() : Vector512.Round(x.As<T, double>()).As<double, T>()),
                29 => (typeof(T) == typeof(float) ? Vector512.Truncate(x.As<T, float>()).As<float, T>() : Vector512.Truncate(x.As<T, double>()).As<double, T>()),
                30 => (typeof(T) == typeof(float) ? Vector512.FusedMultiplyAdd(x.As<T, float>(), y.As<T, float>(), z.As<T, float>()).As<float, T>() : Vector512.FusedMultiplyAdd(x.As<T, double>(), y.As<T, double>(), z.As<T, double>()).As<double, T>()),
                31 => Vector512.IsNaN(x),
                32 => Vector512.IsNegative(x),
                33 => Vector512.IsZero(x),
                _ => x,
            };
            r.StoreUnsafe(ref MemoryMarshal.GetReference(result), (nuint)i);
        }
    }
    private static void RunVec<T>(int op, Span<T> a, Span<T> b, Span<T> c, Span<T> mask, T s, int n, Span<T> result)
        where T : unmanaged, INumber<T>, IBitwiseOperators<T, T, T>
    {
        int count = Vector<T>.Count;
        for (int i = 0; i + count <= a.Length; i += count)
        {
            Vector<T> x = Vector.LoadUnsafe(ref MemoryMarshal.GetReference(a), (nuint)i);
            Vector<T> y = Vector.LoadUnsafe(ref MemoryMarshal.GetReference(b), (nuint)i);
            Vector<T> z = Vector.LoadUnsafe(ref MemoryMarshal.GetReference(c), (nuint)i);
            Vector<T> m = Vector.LoadUnsafe(ref MemoryMarshal.GetReference(mask), (nuint)i);
            Vector<T> r = op switch
            {
                0 => Vector.Add(x, y),
                1 => Vector.Subtract(x, y),
                2 => Vector.Multiply(x, y),
                3 => Vector.Multiply(x, s),
                4 => Vector.Min(x, y),
                5 => Vector.Max(x, y),
                6 => Vector.MinNumber(x, y),
                7 => Vector.MaxNumber(x, y),
                8 => Vector.MaxMagnitude(x, y),
                9 => Vector.Clamp(x, Vector.Min(y, z), Vector.Max(y, z)),
                10 => Vector.Abs(x),
                11 => Vector.Negate(x),
                12 => Vector.Equals(x, y),
                13 => Vector.LessThan(x, y),
                14 => Vector.GreaterThanOrEqual(x, y),
                15 => Vector.ConditionalSelect(m, x, y),
                16 => Vector.BitwiseAnd(x, y),
                17 => Vector.BitwiseOr(x, y),
                18 => Vector.Xor(x, y),
                19 => Vector.AndNot(x, y),
                20 => Vector.OnesComplement(x),
                21 => (x << n),
                22 => (x >> n),
                23 => (x >>> n),
                24 => Vector.CopySign(x, y),
                25 => (typeof(T) == typeof(float) ? Vector.SquareRoot(x.As<T, float>()).As<float, T>() : Vector.SquareRoot(x.As<T, double>()).As<double, T>()),
                26 => (typeof(T) == typeof(float) ? Vector.Floor(x.As<T, float>()).As<float, T>() : Vector.Floor(x.As<T, double>()).As<double, T>()),
                27 => (typeof(T) == typeof(float) ? Vector.Ceiling(x.As<T, float>()).As<float, T>() : Vector.Ceiling(x.As<T, double>()).As<double, T>()),
                28 => (typeof(T) == typeof(float) ? Vector.Round(x.As<T, float>()).As<float, T>() : Vector.Round(x.As<T, double>()).As<double, T>()),
                29 => (typeof(T) == typeof(float) ? Vector.Truncate(x.As<T, float>()).As<float, T>() : Vector.Truncate(x.As<T, double>()).As<double, T>()),
                30 => (typeof(T) == typeof(float) ? Vector.FusedMultiplyAdd(x.As<T, float>(), y.As<T, float>(), z.As<T, float>()).As<float, T>() : Vector.FusedMultiplyAdd(x.As<T, double>(), y.As<T, double>(), z.As<T, double>()).As<double, T>()),
                31 => Vector.IsNaN(x),
                32 => Vector.IsNegative(x),
                33 => Vector.IsZero(x),
                _ => x,
            };
            r.StoreUnsafe(ref MemoryMarshal.GetReference(result), (nuint)i);
        }
    }
}
